### ISSUE TITLE
Latest update has huge errors

### ISSUE THREAD

**Issue by Adam-Cosner** [pop-os/cosmic-comp#1115]
Currently running the latest git commits, and ever since I updated I have to restart multiple times for it to load the compositor, as there are panics and errors blinking on the screen from XWayland and Smithay faster than I can read them

**Comment by Drakulix** [comment]
Can you log into another desktop and post the logs of `journalctl --user _COMM=cosmic-comp`?

**Comment by Adam-Cosner** [comment]
The issue says "thread main panicked at 'No seat?': src/shell/seats.rs:69

**Comment by Tiedye** [comment]
> Can you log into another desktop and post the logs of `journalctl --user _COMM=cosmic-comp`?

From the boot that failed to start:
```
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Failed to read config 'workspaces'
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Unable to become drm master, assuming unprivileged mode
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Failed to set new config.
Jan 06 19:18:56 desktop-linux cosmic-comp[2864]: Unable to become drm master, assuming unprivileged mode
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Failed to set new config.
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Failed to reset config.
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 19:18:57 desktop-linux cosmic-comp[2864]: Xwayland terminated: exit status: 1
```

Then from this session that managed to start (this one), I was trying to change some display settings but they wouldnt save.

```
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Failed to read config 'workspaces'
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Unable to become drm master, assuming unprivileged mode
Jan 06 19:23:43 desktop-linux cosmic-comp[3232]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Jan 06 19:23:44 desktop-linux cosmic-comp[3232]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Jan 06 19:23:44 desktop-linux cosmic-comp[3232]: Unable to become drm master, assuming unprivileged mode
Jan 06 19:23:44 desktop-linux cosmic-comp[3232]: Failed to set new config.
Jan 06 19:23:44 desktop-linux cosmic-comp[3232]: Failed to reset config.
Jan 06 19:24:09 desktop-linux cosmic-comp[3232]: Failed to apply config. Resetting
Jan 06 19:24:09 desktop-linux cosmic-comp[3232]: Failed to reset output config.
Jan 06 19:24:13 desktop-linux cosmic-comp[3232]: Failed to apply config. Resetting
Jan 06 19:24:13 desktop-linux cosmic-comp[3232]: Failed to reset output config.
Jan 06 19:24:16 desktop-linux cosmic-comp[3232]: Failed to apply config. Resetting
Jan 06 19:24:16 desktop-linux cosmic-comp[3232]: Failed to reset output config.
```

From an earlier attempt that failed to start:
```
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: Failed to read config 'workspaces'
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 18:26:10 desktop-linux cosmic-comp[3263]: Unable to become drm master, assuming unprivileged mode
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: failed to create signaled syncobj
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: Unable to become drm master, assuming unprivileged mode
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: thread 'main' panicked at 'No seat?': src/shell/seats.rs:69
                                                    0: <unknown>
                                                    1: <unknown>
                                                    2: <unknown>
                                                    3: <unknown>
                                                    4: <unknown>
                                                    5: <unknown>
                                                    6: <unknown>
                                                    7: <unknown>
                                                    8: <unknown>
                                                    9: <unknown>
                                                   10: <unknown>
                                                   11: <unknown>
                                                   12: <unknown>
                                                   13: <unknown>
                                                   14: <unknown>
                                                   15: <unknown>
                                                   16: <unknown>
                                                   17: <unknown>
                                                   18: <unknown>
                                                   19: __libc_start_main
                                                   20: <unknown>
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 18:26:11 desktop-linux cosmic-comp[3263]: Xwayland terminated: exit status: 1
```

**Comment by elec-n3m** [comment]
I have a similar issue but after reboot it now crashes before the login greeter.

`Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Failed to read config 'workspaces'
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:18:07 serenlab-lt cosmic-comp[2723]: Client bug: Unable to re-configure repositioned popup.
Jan 06 17:18:07 serenlab-lt cosmic-comp[2723]: Client bug: Unable to re-configure repositioned popup.
Jan 06 17:18:10 serenlab-lt cosmic-comp[2723]: Client bug: Unable to re-configure repositioned popup.
-- Boot 8232e239f881473dba3da29556ad44b8 --
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to read config 'workspaces'
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to set new config.
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to reset config.
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to set new config.
Jan 06 17:19:01 serenlab-lt cosmic-comp[2615]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:19:01 serenlab-lt cosmic-comp[2615]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:19:01 serenlab-lt cosmic-comp[2615]: Xwayland terminated: exit status: 1
-- Boot 74382517d6af4dfa9757cb68e439ae7a --
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to read config 'workspaces'
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to set new config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to reset config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to set new config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to reset config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Xwayland terminated: exit status: 1`

**Comment by elec-n3m** [comment]
I have a similar issue but now it crashes before the login greeter.

<details><summary>Details</summary>
<p>

```html
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Failed to read config 'workspaces'
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:00:52 serenlab-lt cosmic-comp[2723]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:18:07 serenlab-lt cosmic-comp[2723]: Client bug: Unable to re-configure repositioned popup.
Jan 06 17:18:07 serenlab-lt cosmic-comp[2723]: Client bug: Unable to re-configure repositioned popup.
Jan 06 17:18:10 serenlab-lt cosmic-comp[2723]: Client bug: Unable to re-configure repositioned popup.
-- Boot 8232e239f881473dba3da29556ad44b8 --
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to read config 'workspaces'
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to set new config.
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to reset config.
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:19:00 serenlab-lt cosmic-comp[2615]: Failed to set new config.
Jan 06 17:19:01 serenlab-lt cosmic-comp[2615]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:19:01 serenlab-lt cosmic-comp[2615]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:19:01 serenlab-lt cosmic-comp[2615]: Xwayland terminated: exit status: 1
-- Boot 74382517d6af4dfa9757cb68e439ae7a --
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to read config 'workspaces'
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to set new config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to reset config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Unable to become drm master, assuming unprivileged mode
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to set new config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to reset config.
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 06 17:21:00 serenlab-lt cosmic-comp[2694]: Xwayland terminated: exit status: 1
``` 

</p>
</details>

**Comment by Adam-Cosner** [comment]
Tracked the general cause down to the switch to the new DrmOutput API

**Comment by nishithshowri006** [comment]
Having the same issue..
![IMG_20250107_120747543](https://github.com/user-attachments/assets/8fdfa91b-30e7-4493-8fb7-deb90a929a47)

**Comment by marchaesen** [comment]
I have the same problem.
The only way I can login is by removing the ~/.config/cosmic folder. But then after logging out, the login fails again.

**Comment by nishithshowri006** [comment]
@marchaesen as a work around I had installed gnome-session, gdm3 for now 😅

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/commit/42af2af37d7443b7e93460d96524ff6b2fa12533 should fix this.

**Comment by marchaesen** [comment]
Unfortunately not. I just tried 7f69244e070282a1dfbaa24c02f9234cb8a2a0b9, and still cosmic-comp failing to start:

cosmic-session[4807]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
/usr/libexec/gdm-wayland-session[4807]: 2025-01-07T12:35:26.160333Z  INFO launch_pad: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
cosmic-comp[4827]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
cosmic-comp[4827]: Key-Binding 'Period' only matched case insensitive for "period"
cosmic-comp[4827]: Key-Binding 'Comma' only matched case insensitive for "comma"
cosmic-comp[4827]: Key-Binding 'Period' only matched case insensitive for "period"
cosmic-comp[4827]: Key-Binding 'Comma' only matched case insensitive for "comma"
cosmic-comp[4827]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
cosmic-comp[4827]: Unable to become drm master, assuming unprivileged mode
cosmic-comp[4827]: Failed to set new config.
cosmic-comp[4827]: Failed to reset config.
cosmic-comp[4827]: Unable to become drm master, assuming unprivileged mode
cosmic-comp[4827]: Failed to set new config.
cosmic-comp[4827]: Failed to reset config.
cosmic-comp[4827]: Failed to restore previous state. Error: Permission denied (os error 13)
cosmic-comp[4827]: Failed to restore previous state. Error: Permission denied (os error 13)
cosmic-comp[4827]: Xwayland terminated: exit status: 1
cosmic-session[4807]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 1
cosmic-session[4807]: cosmic-comp exited with error code 1
/usr/libexec/gdm-wayland-session[4807]: 2025-01-07T12:35:26.552889Z ERROR launch_pad: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 1
/usr/libexec/gdm-wayland-session[4807]: 2025-01-07T12:35:26.552911Z ERROR cosmic_session::comp: cosmic-comp exited with error code 1
/usr/libexec/gdm-wayland-session[4807]: 2025-01-07T12:35:26.552941Z  INFO launch_pad: sleeping for 2ms before restarting process cosmic-comp (restart 0)
cosmic-session[4807]: sleeping for 2ms before restarting process cosmic-comp (restart 0)
cosmic-session[4807]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
/usr/libexec/gdm-wayland-session[4807]: 2025-01-07T12:35:26.556657Z  INFO launch_pad: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
/usr/libexec/gdm-wayland-session[4807]: 2025-01-07T12:35:26.556777Z ERROR cosmic_session::comp: cosmic-comp exited with error code 137
cosmic-session[4807]: cosmic-comp exited with error code 137

**Comment by ViliusP** [comment]
Latest cosmic-comp still crashes, after `rm -rf ~/.local/state/cosmic-comp/outputs.ron`, I can login, but cannot to change display settings (layout and refresh rate changed after deleting that file).

**Comment by Psyhackological** [comment]
I replicated the crash and immediately after: `journalctl --user _COMM=cosmic-comp --since="1 minute ago"`
```text
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Failed to read config 'workspaces'
Jan 07 14:37:20 pop-os cosmic-comp[18982]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 07 14:37:20 pop-os cosmic-comp[18982]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Unable to become drm master, assuming unprivileged mode
Jan 07 14:37:20 pop-os cosmic-comp[18982]: Unable to become drm master, assuming unprivileged mode
Jan 07 14:37:20 pop-os cosmic-comp[18982]: thread 'main' panicked at 'No seat?': src/shell/seats.rs:69
                                              0: <unknown>
                                              1: <unknown>
                                              2: <unknown>
                                              3: <unknown>
                                              4: <unknown>
                                              5: <unknown>
                                              6: <unknown>
                                              7: <unknown>
                                              8: <unknown>
                                              9: <unknown>
                                             10: <unknown>
                                             11: <unknown>
                                             12: <unknown>
                                             13: <unknown>
                                             14: <unknown>
                                             15: <unknown>
                                             16: <unknown>
                                             17: <unknown>
                                             18: __libc_start_call_main
                                                        at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
                                             19: __libc_start_main_impl
                                                        at ./csu/../csu/libc-start.c:360:3
                                             20: <unknown>
Jan 07 14:37:22 pop-os cosmic-comp[18982]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 07 14:37:22 pop-os cosmic-comp[18982]: Failed to restore previous state. Error: Permission denied (os error 13)
Jan 07 14:37:22 pop-os cosmic-comp[18982]: Xwayland terminated: exit status: 1
```

**Comment by Drakulix** [comment]
> I replicated the crash and immediately after: `journalctl --user _COMM=cosmic-comp --since="1 minute ago"`
> 
> ```
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Failed to read config 'workspaces'
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Period' only matched case insensitive for "period"
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Comma' only matched case insensitive for "comma"
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Period' only matched case insensitive for "period"
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Key-Binding 'Comma' only matched case insensitive for "comma"
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Unable to become drm master, assuming unprivileged mode
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: Unable to become drm master, assuming unprivileged mode
> Jan 07 14:37:20 pop-os cosmic-comp[18982]: thread 'main' panicked at 'No seat?': src/shell/seats.rs:69
>                                               0: <unknown>
>                                               1: <unknown>
>                                               2: <unknown>
>                                               3: <unknown>
>                                               4: <unknown>
>                                               5: <unknown>
>                                               6: <unknown>
>                                               7: <unknown>
>                                               8: <unknown>
>                                               9: <unknown>
>                                              10: <unknown>
>                                              11: <unknown>
>                                              12: <unknown>
>                                              13: <unknown>
>                                              14: <unknown>
>                                              15: <unknown>
>                                              16: <unknown>
>                                              17: <unknown>
>                                              18: __libc_start_call_main
>                                                         at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
>                                              19: __libc_start_main_impl
>                                                         at ./csu/../csu/libc-start.c:360:3
>                                              20: <unknown>
> Jan 07 14:37:22 pop-os cosmic-comp[18982]: Failed to restore previous state. Error: Permission denied (os error 13)
> Jan 07 14:37:22 pop-os cosmic-comp[18982]: Failed to restore previous state. Error: Permission denied (os error 13)
> Jan 07 14:37:22 pop-os cosmic-comp[18982]: Xwayland terminated: exit status: 1
> ```

That is the crash that got fixed on master, are you certain you are running the latest commit?

**Comment by Drakulix** [comment]
> Latest cosmic-comp still crashes, after `rm -rf ~/.local/state/cosmic-comp/outputs.ron`, I can login, but cannot to change display settings (layout and refresh rate changed after deleting that file).
> 
> EDIT: Also after reboot, it crashes again, and to login I need to delete that file again.
> 
> ```
> saus. 07 15:12:30 vilius-pc cosmic-comp[2517]: Failed to set new config.
> ```

So this line indicates that some output-settings fail to apply, which would explain the behaviour you are seeing. Can you run `cosmic-comp` with `RUST_BACKTRACE=1` (e.g. on a different tty or by editing `/usr/bin/start-cosmic` so I can figure out, what exactly fails to apply here?

**Comment by mathsDOTearth** [comment]
From an ssh login to the computer with the issue I did:

rich@jam:~$ export RUST_BACKTRACE=1
rich@jam:~$ export DISPLAY=:0
rich@jam:~$ export XAUTHORITY=/run/user/$(id -u)/gdm/Xauthority
rich@jam:~$ export XAUTHORITY=/home/<username>/.Xauthority
-bash: username: No such file or directory
rich@jam:~$ export XAUTHORITY=/home/rich/.Xauthority
rich@jam:~$ export XDG_RUNTIME_DIR=/run/user/$(id -u)
rich@jam:~$ cosmic-comp
2025-01-07T14:22:57.064310Z ERROR cosmic_comp::config: Failed to read config 'workspaces' err=NoConfigDirectory
2025-01-07T14:22:57.068279Z ERROR cosmic_settings_config::shortcuts: failed to read local shortcuts config 'system_actions': NoConfigDirectory
2025-01-07T14:22:57.068430Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Period' only matched case insensitive for "period"
2025-01-07T14:22:57.068454Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Comma' only matched case insensitive for "comma"
2025-01-07T14:22:57.068467Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Period' only matched case insensitive for "period"
2025-01-07T14:22:57.068478Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Comma' only matched case insensitive for "comma"
2025-01-07T14:22:57.068574Z ERROR cosmic_settings_config::shortcuts: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2025-01-07T14:22:57.068962Z ERROR cosmic_settings_config::window_rules: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2025-01-07T14:22:57.077995Z  WARN cosmic_comp::backend: Initializing X11 Backend failed. err=Failed to initilize X11 backend

Caused by:
    0: Connecting to the X server failed
    1: X11 setup failed: 'Authorization required, but no authorization protocol specified
       '

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
   5: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
   6: <unknown>
Authorization required, but no authorization protocol specified

Error: Failed to initilize winit backend: EventLoopCreation(NotSupported(NotSupportedError))

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
   7: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
   8: <unknown>
rich@jam:~$

**Comment by Psyhackological** [comment]
> That is the crash that got fixed on master, are you certain you are running the latest commit?

Ah yeah, sorry, I've just
```bash
cd /tmp
git clone https://github.com/pop-os/cosmic-comp && cd cosmic-comp
make
sudo make install
rm  ~/.local/state/cosmic-comp/outputs.ron
reboot
```
and now everything is working again, thank you!

**Comment by Drakulix** [comment]
> The RUST_BACKTRACE=1 was enabled during this run. But no backtraces were logged. It looks like cosmic-comp did a clean premature exit.

It really should in that case, can you post the output of `journalctl --user -o verbose _COMM=cosmic-comp`?

**Comment by marchaesen** [comment]
I did some more testing.
I am able to login when a remove  ~/.local/state/cosmic-comp/outputs.ron
But when I want to disable one monitor in display settings, I am getting this problem when trying to login again.
Sometimes even disabling one monitor in the settings is not working.

**Comment by marchaesen** [comment]
Attached the verbose log.
[journal2.log](https://github.com/user-attachments/files/18335422/journal2.log)

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/commit/addcbc5039425b0ffc83c95383366e16cbb835d2 should fix another error, that specifically happens on nvidia cards in combination with simpledrm.

**Comment by ViliusP** [comment]
https://github.com/pop-os/cosmic-comp/commit/addcbc5039425b0ffc83c95383366e16cbb835d2 fixed problems for me. Now I can successfully login and change settings. Thanks.

**Comment by Adam-Cosner** [comment]
Yup, looks good now, thanks for fixing it!

**Comment by marchaesen** [comment]
Latest commit fixed problem for me to. Thanks.
