### ISSUE TITLE
[Bug] Multi-monitor re-connection causes panel/dock visibility issues and workspace inconsistencies

### ISSUE THREAD

**Issue by tealsnow** [pop-os/cosmic-comp#1470]
In a multi-monitor setup (e.g., Main Monitor A and Secondary Monitor B), when a window is located on Secondary Monitor B and that monitor is unplugged, the window correctly moves to Main Monitor A. However, upon re-connecting Secondary Monitor B, the window moves back to its original position on Monitor B, but this process introduces two significant issues:

1. Panel and Dock Visibility Glitch: The panel and dock, which are configured to auto-hide, remain visible and overlap the returned window on Monitor B. They do not hide as expected, obscuring parts of the application.
2. Pinned Workspaces Disappear in Overview: All pinned workspaces vanish from the workspace overview (e.g., if Workspaces 1 and 2 were pinned, only Workspace 3 becomes visible in the overview after the re-connection). Interestingly, all three workspaces still correctly appear in the panel's workspace indicator (which is now covering the window). If a new window is subsequently opened on Workspace 3, a fourth workspace appears as expected, and the panel and dock correctly auto-hide (for this and new workspaces only).

## Steps to Reproduce

1. Set up a multi-monitor environment (e.g., Laptop display as Main Monitor A, external display as Secondary Monitor B).
2. Ensure that the panel and dock are configured to auto-hide.
3. Move an application window to Secondary Monitor B.
4. Unplug Secondary Monitor B. Observe that the window moves to Main Monitor A.
5. Plug Secondary Monitor B back in. Observe that the window returns to Monitor B.
6. **Verify Issues:**
    - Notice that the panel and dock on Monitor B remain visible and overlap the window, despite auto-hide settings.
    - Open the workspace overview. Observe that only unpinned workspaces (e.g., Workspace 3) are visible, while previously pinned workspaces (e.g., 1 and 2) are gone from the overview.

## Expected Behaviour

Upon re-connection of a secondary monitor:

1. Windows should return to their original positions without affecting the auto-hide behaviour of the panel and dock. The panel and dock should hide correctly if the window is maximised or covers their area.
2. All previously pinned workspaces should remain visible and accessible in the workspace overview.
3. The system should maintain consistent workspace behaviour (e.g., panel, dock, and overview synchronisation) after monitor re-connection.

**Comment by ids1024** [comment]
At least some of this should be fixed by https://github.com/pop-os/cosmic-comp/pull/1496. Though perhaps there are still issues in some circumstances.

**Comment by tealsnow** [comment]
> At least some of this should be fixed by [#1496](https://github.com/pop-os/cosmic-comp/pull/1496). Though perhaps there are still issues in some circumstances.

I know I'm a little late to reply, but I can confirm the issue of the panels not hiding from windows is still an issue as of alpha 7.

<details><summary>Details</summary>
<p>
<img width="1360" height="768" alt="Image" src="https://github.com/user-attachments/assets/0b062e9b-867a-473e-92fd-b04553d51501" />
</p>
</details>

It's real annoying, as cosmic is the only DE that lets me have separate workspaces per monitor. And every time I plug in my monitor, I have to log out and back in again.
