### ISSUE TITLE
Everything freezes when I plug in my USB-C hub since last update

### ISSUE THREAD

**Issue by fstanis** [pop-os/cosmic-comp#1631]
Hey all, last night I updated packages in my system and since then I'm having trouble with connecting an external display using my USB-C hub.

Specifically, as soon as I connect the USB-C cable, everything freezes and the system becomes unusable (even the clock stops moving). At that point, I need to do a hard reset (hold the power button on the laptop), plugging it out doesn't help.

A workaround I found is that if I switch to a different TTY by pressing Ctrl+Alt+F2, then connect  the hub and wait for the terminal to appear on my external display, then switch back via Ctrl+Alt+F1, everything works. If the computer goes to sleep and then returns, it freezes again.

I'm not finding anything useful in `journalctl` - here's everything that happened when I plugged in my hub (I started `dmesg` a moment prior so I can see the exact moment):

```
Sep 09 11:37:36 pop-laptop sudo[4764]: user : TTY=pts/0 ; PWD=/home/user ; USER=root ; COMMAND=/usr/bin/dmesg -w
Sep 09 11:37:36 pop-laptop sudo[4764]: pam_unix(sudo:session): session opened for user root(uid=0) by user(uid=1000)
Sep 09 11:37:36 pop-laptop cosmic-panel[2034]: com.system76.CosmicAppletStatusArea: Skipping invalid icon: 0x0 with 0 bytes, app may still be initializing
Sep 09 11:37:41 pop-laptop tailscaled[1741]: health(warnable=no-derp-connection): ok
Sep 09 11:37:51 pop-laptop tailscaled[1741]: health(warnable=no-derp-connection): error: Tailscale could not connect to the 'London' relay server. Your Internet connection might be down, or the server might be temporarily unavailable.
Sep 09 11:37:55 pop-laptop kernel: usb 4-1: new SuperSpeed Plus Gen 2x1 USB device number 2 using xhci_hcd
Sep 09 11:37:55 pop-laptop kernel: usb 4-1: New USB device found, idVendor=05e3, idProduct=0625, bcdDevice=64.00
Sep 09 11:37:55 pop-laptop kernel: usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 09 11:37:55 pop-laptop kernel: usb 4-1: Product: USB3.2 Hub
Sep 09 11:37:55 pop-laptop kernel: usb 4-1: Manufacturer: GenesysLogic
Sep 09 11:37:55 pop-laptop kernel: hub 4-1:1.0: USB hub found
Sep 09 11:37:55 pop-laptop kernel: hub 4-1:1.0: 4 ports detected
Sep 09 11:37:56 pop-laptop kernel: usb 3-1: new high-speed USB device number 3 using xhci_hcd
Sep 09 11:37:56 pop-laptop kernel: usb 3-1: New USB device found, idVendor=05e3, idProduct=0610, bcdDevice=64.00
Sep 09 11:37:56 pop-laptop kernel: usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 09 11:37:56 pop-laptop kernel: usb 3-1: Product: USB2.1 Hub
Sep 09 11:37:56 pop-laptop kernel: usb 3-1: Manufacturer: GenesysLogic
Sep 09 11:37:56 pop-laptop kernel: hub 3-1:1.0: USB hub found
Sep 09 11:37:56 pop-laptop kernel: hub 3-1:1.0: 4 ports detected
Sep 09 11:37:56 pop-laptop fwupd[4491]: 10:37:56.778 FuEngine             failed to add device usb:03:00:01: no CFI device found
Sep 09 11:38:11 pop-laptop kernel: usb 3-1: USB disconnect, device number 3
Sep 09 11:38:11 pop-laptop kernel: usb 4-1: USB disconnect, device number 2
Sep 09 11:38:41 pop-laptop tailscaled[1741]: health(warnable=no-derp-connection): ok
Sep 09 11:38:51 pop-laptop tailscaled[1741]: health(warnable=no-derp-connection): error: Tailscale could not connect to the 'London' relay server. Your Internet connection might be down, or the server might be temporarily unavailable.
```

It seems background services kept running, i.e. tailscale, but the screen stopped updating.

Here's the relevant update from `/var/log/apt/history.log` that broke it:
```
Start-Date: 2025-09-09  01:53:37
Commandline: packagekit role='update-packages'
Requested-By: user (1000)
Upgrade: cosmic-greeter:amd64 (0.1.0~1753826646~24.04~b848d52, 0.1.0~1757250084~24.04~da11207), xserver-xorg-video-nouveau:amd64 (1:1.0.17-2build1, 1:1.0.17-2ubuntu0.1), cosmic-settings-daemon:amd64 (0.1.0~1753129403~24.04~f4f4fb3, 0.1.0~1756936548~24.04~ff15f32), python3.12:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), libglx-mesa0:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), cosmic-comp:amd64 (0.1~1753987246~24.04~e1aa8f7, 0.1~1757335626~24.04~7684cd1), cosmic-app-library:amd64 (0.1.0~1753910863~24.04~795c47f, 0.1.0~1757355962~24.04~893fe70), mesa-common-dev:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), google-chrome-stable:amd64 (139.0.7258.66-1, 140.0.7339.80-1), libgtk-4-common:amd64 (4.14.5+ds-0ubuntu0.4, 4.14.5+ds-0ubuntu0.5), cosmic-term:amd64 (0.1.0~1753910846~24.04~a22c1cf, 0.1.0~1755123295~24.04~555e1ae), libxml2-dev:amd64 (2.9.14+dfsg-1.3ubuntu3.3, 2.9.14+dfsg-1.3ubuntu3.4), libldb2:amd64 (2:2.8.0+samba4.19.5+dfsg-4ubuntu9.2, 2:2.8.0+samba4.19.5+dfsg-4ubuntu9.3), cosmic-panel:amd64 (0.1.0~1753837892~24.04~da27f53, 0.1.0~1757335801~24.04~2bd1a6f), gstreamer1.0-gl:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), libpoppler-cpp0t64:amd64 (24.02.0-1ubuntu9.5, 24.02.0-1ubuntu9.6), libgbm1:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), cosmic-randr:amd64 (0.1.0~1744718623~24.04~c32d0d6, 0.1.0~1757248943~24.04~bce9cdf), libmalcontent-0-0:amd64 (0.11.1-1ubuntu1.1, 0.11.1-1ubuntu1.2), bluez-cups:amd64 (5.72-0ubuntu5.3, 5.72-0ubuntu5.4), system76-power:amd64 (1.2.7~1753385894~24.04~f88eeb1, 1.2.7~1755014225~24.04~b72813c), libpython3.12-minimal:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), mesa-libgallium:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), cosmic-files:amd64 (0.1.0~1753977874~24.04~4f015ee, 0.1.0~1755744274~24.04~f06029f), libjavascriptcoregtk-4.1-0:amd64 (2.48.3-0ubuntu0.24.04.1, 2.48.5-0ubuntu0.24.04.1), libtiff6:amd64 (4.5.1+git230720-4ubuntu2.2, 4.5.1+git230720-4ubuntu2.3), software-properties-common:amd64 (0.99.49.2, 0.99.49.3), udisks2:amd64 (2.10.1-6ubuntu1.2, 2.10.1-6ubuntu1.3), libgstreamer-gl1.0-0:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), libwbclient0:amd64 (2:4.19.5+dfsg-4ubuntu9.2, 2:4.19.5+dfsg-4ubuntu9.3), gstreamer1.0-plugins-base-apps:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), python3-software-properties:amd64 (0.99.49.2, 0.99.49.3), libxatracker2:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), cosmic-edit:amd64 (0.1.0~1753910878~24.04~8d1a986, 0.1.0~1756071470~24.04~7d279a1), xserver-xorg-video-vesa:amd64 (1:2.6.0-1, 1:2.6.0-1ubuntu0.1), libxml2:amd64 (2.9.14+dfsg-1.3ubuntu3.3, 2.9.14+dfsg-1.3ubuntu3.4), gstreamer1.0-alsa:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), python3.12-venv:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), cosmic-bg:amd64 (0.1.0~1746111618~24.04~1da843a, 0.1.0~1756826102~24.04~6841c5a), cosmic-greeter-daemon:amd64 (0.1.0~1753826646~24.04~b848d52, 0.1.0~1757250084~24.04~da11207), mesa-va-drivers:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), poppler-utils:amd64 (24.02.0-1ubuntu9.5, 24.02.0-1ubuntu9.6), libgl1-mesa-dri:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), python3-repolib:amd64 (2.2.2~1753810292~24.04~7f0e7f5, 2.2.2~1755270712~24.04~fe51095), libpython3.12t64:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), libgstreamer-plugins-good1.0-0:amd64 (1.24.2-1ubuntu1.1, 1.24.2-1ubuntu1.2), libudisks2-0:amd64 (2.10.1-6ubuntu1.2, 2.10.1-6ubuntu1.3), gstreamer1.0-x:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), cosmic-initial-setup:amd64 (0.1.0~1753803072~24.04~083af55, 0.1.0~1756946798~24.04~fb6b147), cosmic-applets:amd64 (0.1.0~1753989808~24.04~19e750c, 0.1.0~1757249937~24.04~93735b1), libsmbclient0:amd64 (2:4.19.5+dfsg-4ubuntu9.2, 2:4.19.5+dfsg-4ubuntu9.3), gstreamer1.0-plugins-good:amd64 (1.24.2-1ubuntu1.1, 1.24.2-1ubuntu1.2), gstreamer1.0-plugins-base:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), libpoppler134:amd64 (24.02.0-1ubuntu9.5, 24.02.0-1ubuntu9.6), mesa-vulkan-drivers:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), cosmic-workspaces:amd64 (0.1.0~1750899258~24.04~30ca652, 0.1.0~1757249962~24.04~05c9af1), cosmic-osd:amd64 (0.1.0~1753392154~24.04~78e4f7c, 0.1.0~1757249857~24.04~f826e11), cosmic-launcher:amd64 (0.1.0~1753829861~24.04~2831b8c, 0.1.0~1757249901~24.04~e2aa2aa), libwebkit2gtk-4.1-0:amd64 (2.48.3-0ubuntu0.24.04.1, 2.48.5-0ubuntu0.24.04.1), libmalcontent-0-dev:amd64 (0.11.1-1ubuntu1.1, 0.11.1-1ubuntu1.2), gir1.2-malcontent-0:amd64 (0.11.1-1ubuntu1.1, 0.11.1-1ubuntu1.2), cosmic-settings:amd64 (0.1.0~1753975390~24.04~a0f7b31, 0.1.0~1757357021~24.04~bd7fc2a), xdg-desktop-portal-cosmic:amd64 (0.1.0pop1~1753452772~24.04~a9e8731, 0.1.0pop1~1756825407~24.04~de1f131), libbluetooth3:amd64 (5.72-0ubuntu5.3, 5.72-0ubuntu5.4), libpython3.12-dev:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), cosmic-store:amd64 (0.1.0~1753826702~24.04~cfdff01, 0.1.0~1757266150~24.04~2f9bf1e), simple-scan:amd64 (46.0-0ubuntu2, 46.0-0ubuntu2.1), libgtk-4-1:amd64 (4.14.5+ds-0ubuntu0.4, 4.14.5+ds-0ubuntu0.5), samba-libs:amd64 (2:4.19.5+dfsg-4ubuntu9.2, 2:4.19.5+dfsg-4ubuntu9.3), python3.12-dev:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), code:amd64 (1.102.3-1753759567, 1.103.2-1755709794), bluez:amd64 (5.72-0ubuntu5.3, 5.72-0ubuntu5.4), libegl-mesa0:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), libpoppler-glib8t64:amd64 (24.02.0-1ubuntu9.5, 24.02.0-1ubuntu9.6), libgtk-4-bin:amd64 (4.14.5+ds-0ubuntu0.4, 4.14.5+ds-0ubuntu0.5), libgtk-4-media-gstreamer:amd64 (4.14.5+ds-0ubuntu0.4, 4.14.5+ds-0ubuntu0.5), python3.12-minimal:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), libgstreamer-plugins-base1.0-0:amd64 (1.24.2-1ubuntu0.2, 1.24.2-1ubuntu0.3), gcc-12-base:amd64 (12.3.0-17ubuntu1, 12.4.0-2ubuntu1~24.04), mesa-vdpau-drivers:amd64 (25.0.5-1pop1~1747633989~24.04~be49689, 25.1.5-1pop0~1753463422~24.04~8af185e), libpython3.12-stdlib:amd64 (3.12.3-1ubuntu0.7, 3.12.3-1ubuntu0.8), cosmic-session:amd64 (0.1.0~1749848508~24.04~b2f4277, 0.1.0~1757100934~24.04~2441be2), intel-media-va-driver:amd64 (24.1.0+dfsg1-1, 24.1.0+dfsg1-1ubuntu0.1), libgcc-12-dev:amd64 (12.3.0-17ubuntu1, 12.4.0-2ubuntu1~24.04), libstdc++-12-dev:amd64 (12.3.0-17ubuntu1, 12.4.0-2ubuntu1~24.04)
End-Date: 2025-09-09  01:54:19
```

FWIW, the hub in question is `UGREEN Uno USB C Hub, 6-in-1`, it happens even when there are no USB devices plugged into it.

I'm not 100% sure this is a compositor issue since the logs aren't really showing anything, just a hunch based on the behaviour - let me know if there's anything else I can check or upload.

**Comment by Drakulix** [comment]
Can you post compositor logs from when this happens?
`journalctl --user _COMM=cosmic-comp`

**Comment by fstanis** [comment]
Hi, there aren't any when it happens - the `journalctl` I posted was all the combined logs. Can I enable some kind of verbose mode?

I managed to run `drm_info` via `sleep 10 && drm_info > drm_info_freeze.txt` here: [drm_info_freeze.txt](https://github.com/user-attachments/files/22234429/drm_info_freeze.txt)

Here's `drm_info` with the same hub and screen connected (using the TTY switch workaround):[drm_info_working.txt](https://github.com/user-attachments/files/22234430/drm_info_working.txt)

**Comment by Drakulix** [comment]
> Hi, there aren't any when it happens - the `journalctl` I posted was all the combined logs. Can I enable some kind of verbose mode?

The only way to get more logs is to do a debug-build of cosmic-comp. But the logs are from the user-session not from the system session, so the command I posted might still be different than a combined journalctl-log.

However if there is no output, that hints towards a kernel issue more than a compositor issue.

The working log suggests that you disable your internal output, when this works. So possibly something wrong is going on disabling one while enabling the other.

Does the problem go away, if you (re)move `.local/state/cosmic-comp/outputs.ron`? (Please don't simply delete the file, it contains your output configuration. If this solves the problem, the contents might provide valuable insight in figuring out, how to replicate your issue.)

**Comment by fstanis** [comment]
Removing `outputs.ron` "fixed" it! At least, the screen works in extended mode now and doesn't freeze. Turning off either the internal screen or the external monitor in settings causes it to immediately freeze, however.

These are the logs for `cosmic-comp` when it happened - however, the same message is happening regularly regardless.
```
Sep 09 15:09:32 pop-laptop cosmic-comp[1920]: Client bug: Unable to re-configure repositioned popup.
Sep 09 15:09:32 pop-laptop cosmic-comp[1920]: Client bug: Unable to re-configure repositioned popup.
Sep 09 15:09:32 pop-laptop cosmic-comp[1920]: Client bug: Unable to re-configure repositioned popup.
```

Edit: simply doing `cosmic-randr disable DP-2` is the easiest way to repro this right now.

**Comment by Drakulix** [comment]
Looking at your apt-history, the commit listed for cosmic-comp is https://github.com/pop-os/cosmic-comp/commit/e1aa8f7 from July. There have been numerous updates to the output-logic since then and this issue looks very familiar. I am not sure why the system would downgrade you to such a low version. Do you have any other repositories enabled than the default set?

**Comment by fstanis** [comment]
Maybe I'm not reading it correctly, but I thought https://github.com/pop-os/cosmic-comp/commit/e1aa8f7 is the version I upgraded from? Whereas https://github.com/pop-os/cosmic-comp/commit/7684cd1 is the one I have now?

Do you know if there's an (easy) way to revert to an earlier version BTW? I got this error when I tried:
```
$ sudo apt install cosmic-comp=0.1~1753987246~24.04~e1aa8f7
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package cosmic-comp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '0.1~1753987246~24.04~e1aa8f7' for 'cosmic-comp' was not found
```
If I can downgrade easily, I could probably go through the previous builds and find where the regression happened.

**Comment by Drakulix** [comment]
> Maybe I'm not reading it correctly, but I thought [e1aa8f7](https://github.com/pop-os/cosmic-comp/commit/e1aa8f7) is the version I upgraded from? Whereas [7684cd1](https://github.com/pop-os/cosmic-comp/commit/7684cd1) is the one I have now?

No, you are right, that was a misread by me.

Honestly with the amount of changes in between these two versions, bisecting might be very cumbersome.

I have however been able to reproduce the issue by disabling an output (I didn't have the freeze when adding another output, possibly because I had no configuration with a disabled output, like you had before).

So this gives me an easy way to debug and hopefully quickly fix this. Could you also upload your "broken" outputs.ron file?

**Comment by fstanis** [comment]
> Could you also upload your "broken" outputs.ron file?

I've unfortunately deleted it after getting to one that works 🤦  The only setting that I'd changed was disabling the built-in screen, which is consistent with what happens when I try to disable it via settings. I could try to recreate it if that helps?

**Comment by tmshlvck** [comment]
I am experiencing the exact same issue on my Lenovo T14s laptop with AMD Ryzen 7 PRO 4750U with Radeon Graphics and with a Dell external screen. There is freeze on eDP-1 disable (no matter if I just close lid or use GUI or `cosmic-randr`), no records are logged after the freeze in both user or system journal.

I have
```
th@hroch:~$ dpkg -l | grep cosmic-comp
ii  cosmic-comp                                    0.1~1757335626~24.04~7684cd1                                    amd64        Wayland compositor of pop-os cosmic shell
```

My original `outputs.ron` that caused freeze on monitor plug-in follows. The difference between instant freeze and no-freeze is the `enabled: r#false,` for the eDP-1:
```
(
    config: {
        [
            (
                connector: "DP-2",
                make: "Dell Inc.",
                model: "DELL U4021QW",
            ),
            (
                connector: "eDP-1",
                make: "AU Optronics",
                model: "0x573D",
            ),
        ]: [
            (
                mode: ((5120, 2160), Some(59985)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (1920, 0),
                enabled: r#true,
                max_bpc: Some(16),
                xwayland_primary: false,
            ),
            (
                mode: ((1920, 1080), Some(60033)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#false,
                max_bpc: Some(16),
                xwayland_primary: true,
            ),
        ],
        [
            (
                connector: "eDP-1",
                make: "AU Optronics",
                model: "0x573D",
            ),
        ]: [
            (
                mode: ((1920, 1080), Some(60033)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(16),
                xwayland_primary: true,
            ),
        ],
    },
)
```

**Comment by nimaim** [comment]
Same issue here, on an Alienware M16 R1 with hybrid graphics (4070 + 13700HX iGPU). Removing outputs.ron fixes it and re-enables displays on a post reboot session, but as previously reported, playing around in display settings disabling/enabling displays re-triggers the error.

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/pull/1632 should fix the issue, can somebody test and confirm?

**Comment by pdanpdan** [comment]
Was the proposed fix implemented in cosmic-comp ~458f5f4?
Because the crashes/freezes still happen.

**Comment by Drakulix** [comment]
No the linked pull request isn't merged yet.

**Comment by tmshlvck** [comment]
https://github.com/pop-os/cosmic-comp/pull/1632 fixed the freezes for me.

Thank you for your exceptional work!

**Comment by jacobktm** [comment]
https://github.com/pop-os/cosmic-comp/pull/1632 fixed this issue on another system I saw it on as well
