### ISSUE TITLE
Desktop scaling 125%, new windows for some apps appear not centered, offset to the right and partially outside of visible desktop area

### ISSUE THREAD

**Issue by cz4rr** [pop-os/cosmic-comp#1639]
Showing an example with a game but happens also with VLC video playback:

[https://www.reddit.com/r/pop_os/comments/1nfi141/comment/ndwu86t/](url)

Tried resolving this with X11 window application scaling options:

- optimize for gaming and full-screen apps - no change
- optimize for apps - no change
- maximum compatibility - fixed but everything is now blurry

Arch Linux, latest Cosmic build from ChaoticAUR. Let me know and I will provide additional details if needed.

**Comment by WatchMkr** [comment]
This should be fixed with the `epoch-1.0.0-beta.1.1` cosmic-comp release when updated in the repo.

**Comment by cz4rr** [comment]
@WatchMkr 
pacman -Q | grep cosmic-session
cosmic-session 1.0.0.beta.1.1-1
Unfortunately not fixed. Did some additional testing and it also happens with scaling @ 100%,
I'm doing simple test - opening movie in VLC. Window always appears stretched to the right and bottom beyond desktop view port.
SUPER+M centers window immediately and fits nicely on desktop.

**Comment by WatchMkr** [comment]
I see this with some games (Goat Simulator is one). Thought it might be related to https://github.com/pop-os/cosmic-comp/issues/1510 but may be a separate issue.

**Comment by cz4rr** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/cb4f7a32-5269-447c-bf70-9660129a6d6a" />

> I see this with some games (Goat Simulator is one). Thought it might be related to [#1510](https://github.com/pop-os/cosmic-comp/issues/1510) but may be a separate issue.

To me it looks like all QT applications are affected by this issue. I believe VLC GUI is also built with this toolkit. 
Other example application I'm using is ClassicImageViewer (also QT): 

To reproduce:
-  install ClassicImageViewer application and open any image 

Actual result: 
- app window always appears slightly offset to the right from screen center point and about 1/8th of the screen from the top
- if image is small enough window fits the remaining screen space
- if image is big enough window is stretched to the right and to the bottom outside of visible screen space

Expected:
- window should appear centered for small images, maximized for big images and should fit the screen

**Comment by cz4rr** [comment]
Regarding gaming I'm using Lutris to launch titles and have had mixed luck with this - some of titles appear centered in window mode, some e.g. Diablo II have same exact issue. 
Edit: seems winecfg setting "Allow the window manager to decorate the windows" causes issue to appear with certain games in window mode.

**Comment by cz4rr** [comment]
@WatchMkr 
Workaround for QT5 apps: 
Install [QAdwaitaDecorations](https://github.com/FedoraQt/QAdwaitaDecorations) plugin. 
export QT_WAYLAND_DECORATION=adwaita

As it turns out this Qt decoration plugin implementing Adwaita-like client-side decorations also resolves this issue (tested with QT5 ClassicImageViewer application - screenshot attached)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/be83c3d1-5103-4103-b7f0-3eaa51ea40a5" />

**Comment by IgKh** [comment]
Few extra notes on the issue, hopefully useful.

I am able to reliably reproduce the issue with ClassicImageViewer, built from the latest commit in https://github.com/classicimageviewer/ClassicImageViewer (c30da71 at the time of writing), built against Qt 6.10.0. And the important bit is that in the application settings dialog, Display > Display mode has to be set to the first option - "Fit window to images".

I believe the issue has to be with windows that start small but attempt to resize themselves larger (by the application's volition, not though user interaction) at a later point.

Interestingly enough, I can see the same effect in **KDE Plasma** (with KWin being the compositor):

https://github.com/user-attachments/assets/00b8e2ae-7fb8-4fe1-880e-8703c2cb9edd

Under KDE the issue appears when using Wayland directly, but works fine via XWayland (that is - the window appears as large as allowed, covering all of the screen area not taken by the bar without being in a maximized state). In COSMIC - both direct and XWayland show the issue.

It could be a coincidence, a protocol violation on the side of the application, or a more fundamental problem with the xdg-shell protocol: can't tell at this point. I've taken `WAYLAND_DEBUG=1` traces under both environments and attached them here. There doesn't seem to be much obviously wrong at first sight - the `xdg_surface.set_window_geometry` call setting the larger size is not in response to a `configure` signal, but that seems to be allowed by the protocol? Do note that in the trace taken under cosmic-comp, a later `configure` signal arrives with the old size as the suggested dimensions - showing the the resize didn't "stick" (although evidently the new buffer is bigger).

[civ-trace-cosmic.log](https://github.com/user-attachments/files/22942196/civ-trace-cosmic.log)
[civ-trace-kde.log](https://github.com/user-attachments/files/22942195/civ-trace-kde.log)
