### ISSUE TITLE
mouse starts spinning while playing games with proton

### ISSUE THREAD

**Issue by kurai111** [pop-os/cosmic-comp#1692]
the same thing happens on multiple games but im putting gw2 as an example
https://imgur.com/a/7SS9STI

when i reboot everything is fine but after a few hours this starts happening.the camera will look up and wont let me look down,when i hold right click and try to move it randomly spins. restarting the game/changing proton versions doesnt help

i am using cachyos. i switched to cosmic 1 week ago i was using xfce before and this never happened.

**Comment by kurai111** [comment]
apparently this was an issue in kde too but got fixed https://bugs.kde.org/show_bug.cgi?id=482476

**Comment by kurai111** [comment]
another thing i found.i tried playing dead by daylight and when i tried to move my camera to right,it wouldnt let me move,only 30 degrees or something.then i clicked super button and clicked on game window and it let me do a 360 degree turn then got stuck again.heres the video: https://imgur.com/a/8jbDBpg

very weird

**Comment by ids1024** [comment]
I seem to see similar behavior in some games, but not others. And at least temporarily fixed by restarting the compositor.

Good catch on the KDE issue; that looks very similar.

**Comment by ids1024** [comment]
If it doesn't happen when the compositor initially starts, it would be good to identify exactly what makes the problem start...

**Comment by kurai111** [comment]
i really have no idea because it happens so randomly.sometimes i can play entire day without this happening sometimes it happens twice a day

**Comment by ids1024** [comment]
Yeah. It's annoying. I've seen this, but trying various things, I can't reproduce it. The KDE issue sounds similar, but we don't seem to be generating `relative_motion` events for warps, so a change like https://invent.kde.org/plasma/kwin/-/commit/630ba5fab4b02c2b496553c79d4a315da9271b53 per se isn't needed.

**Comment by Sirius902** [comment]
I've had this issue occur several times when playing FFXIV (usually I notice it when I first open the game after a while of not having it open so presumably something I've done prior to that point triggered it). However, I have found an odd workaround to fix the issue after it happens in FFXIV:
- Ensure that you have the issue triggered first (trying to move the camera by clicking and panning the mouse results in the camera spinning wildly out of control) and that you have a dual monitor setup with the game on the right monitor.
- Next, click into the game window and hold down the left mouse button to allow the camera to be moved (do not release the mouse button).
- Activate the "Focus window left" navigation keyboard shortcut (Super+h by default) which moves the mouse cursor instantly to the center of the left monitor.
- Move the mouse around a little (I'm not sure if this step is necessary but I think I ended up doing this).
- You may now release the left mouse button now, when trying to pan the camera in game again you'll notice that the issue is no longer present (camera moves as expected).

**Comment by skygrango** [comment]
I’ve occasionally encountered this issue in various games played through Proton. When it occurs, if I switch the game to windowed mode using shortcut key( Super + F11), the mouse can freely move outside the game window instead of being confined within it(Under normal circumstances, even when the game is in windowed mode, the mouse cannot leave the game window's viewport). I suspect that the mouse focus has lost its association with the game window.

note: even restarting the game doesn’t resolve this issue, so it’s possible that under certain conditions, cosmic-comp loses the mouse focus state when handling fullscreen windows.

**Comment by kurai111** [comment]
since last week this started to happen way more frequently.sometimes it even happens right after i boot my pc

**Comment by kylekyleton** [comment]
This happens to me often. 
Leaving fullscreen and then re-entering fullscreen using the `Super + F11` shortcut _usually_ resolves it.
The times that it doesn't resolve with that trick, I fix it by leaving fullscreen, then using the "move window" shortcuts in tiling mode to send the game window to another screen (I have three displays) and back again to re-enable fullscreen, or by opening some other app and moving the game window around the same display, then going fullscreen again. 
It's only a per-session fix though; it's somewhat annoying to have to do it but I have always been able to resolve it using these tricks.

**Comment by hm7D2** [comment]
I got the same issue and unfortunately none of the mentioned workarounds in this thread have helped me. I am able to trigger this consistently by closing or minimizing an open steam or discord window, does not matter if i did it hours before opening the game or while having it running. Also happens from time to time without having done any action i would know about

**Comment by WatchMkr** [comment]
This was probably solved with the implementation of Wayland's pointer constraints protocol this week. CachyOS is pretty quick to pick up releases so you should see it soon.

**Comment by GoneDog** [comment]
I'm still having this issue in several games - notably Deus Ex GOTY, Vampire: Bloodlines, Manhunt, and Unreal Tournament. Rust and SW: Outlaws run fine, but, sometimes launch off-center before fullscreen takes effect -- also, I have to turn on my Xbox controller and wiggle the stick before my mouse will control the camera. Pop OS/Liqourix

UPDATE: adding    PROTON_ENABLE_WAYLAND=1 %command%     to launch option s fixed this for me

**Comment by gnamily** [comment]
I've had this issue still on FFXIV, the workaround of moving window focus while holding the mouse down button seems to fix it for me. 
I'm on cosmic-comp 1:1.3.0-1.1 on CachyOS

**Comment by Zackey** [comment]
I also have this issue,  PROTON_ENABLE_WAYLAND=1 %command% did not resolve it but spamming super + f11 worked fine.

**Comment by Chubbynerdatduck2027** [comment]
> I also have this issue, PROTON_ENABLE_WAYLAND=1 %command% did not resolve it but spamming super + f11 worked fine.

can confirm that when I used super + f11 twice in this method mentioned above and moved my mouse around in the windowed mode then moved it around in fullscreen after hitting super + f11 a third time Im actually able to play sniper elite 2 this way with updated proton 9.04 thanks again for this useful info! <3

**Comment by Zackey** [comment]
This is still a huge issue on PopOS for me across every game, any chance of a fix? @WatchMkr
