### ISSUE TITLE
Fullscreen XWayland apps mouse capture issue

### ISSUE THREAD

**Issue by Adam-Cosner** [pop-os/cosmic-comp#1874]
This is a recurring issue that has been fixed multiple times and has returned again. Mouse movement in 3D games which usually relies on resetting mouse cursor position is not able to do so as of a couple days ago, so when you're in a game and you turn your view too far in one direction, it ends up hitting a wall that you can't move past.

**Comment by Adam-Cosner** [comment]
Seems to be gone again

**Comment by Adam-Cosner** [comment]
Nevermind, it's doing it again. I'm not exactly sure what is causing it, I'll try and see if I can consistently recreate the behavior

**Comment by Adam-Cosner** [comment]
Okay, it seems that there's a trigger of some sort that causes it to become broken for the rest of the session and is only able to be fixed by restarting the compositor

**Comment by Hyperchaotic** [comment]
I wonder is that the problem I've been seeing for a week or so in GuildWars2 (Proton+XWayland), when I adjust camera angle. 

At first everything works fine but some time into the game (it could be after a few minutes or 15, etc) when I try to adjust the view angle it snaps down and stays there, it just flips around there when I try to adjust the view. As can be seen at the end of the video if I bring up a menu with a hotkey the mouse works fine while visible.

Happens in windowed mode as well.

https://github.com/user-attachments/assets/2d3f1cda-5e2f-453b-95fc-17396002e321

**Comment by jstelzer** [comment]
Just chiming in with some of my own observations about games interacting with the compositor. What's worked and whats been weird. 

**Environment**

* COSMIC (Wayland compositor)
* NVIDIA proprietary driver
* gamescope involved (sometimes)
* XWayland for most FPS titles

**Works**

* Controller-driven games (SDL / evdev path)
* WoW-style *modal* relative mouse (enter/exit camera mode)
* games that don t require continuous relative motion

**Fails**

* FPS games requiring **continuous relative mouse motion**
* Symptoms:

  * invisible left/right rotation boundary
  * partial pointer confinement
  * grab appears active but motion clamps
  * KDE/KWin does not exhibit the issue

**Key insight**

> This is not a game bug, not a Wine bug, not a gamescope flag issue   it s a compositor-level gap in handling continuous relative pointer semantics under Wayland. Specifically Xwayland.

*  FPS games using continuous relative mouse hit invisible rotation bounds 
*  Does not reproduce on KDE Plasma Wayland (KWin) 
*  Reproduces on COSMIC Wayland Borderlands4, Doom  
*  gamescope `--relative-mouse` and `--force-grab-cursor` mitigate but do not fully resolve 
*  Modal relative mouse (WoW/Baldurs Gate 3 camera mode) works correctly 
* GPU: NVIDIA proprietary
* Session: Wayland
* Input: mouse only (controller unaffected)
* Controler based games like Elden Ring/Souls types are unaffected because sdl/evpath are outside the compositor basically.


I have verified that setting PROTON_ENABLE_WAYLAND=1 fixes the issue for borderlands 4.

**Comment by silentTeee** [comment]
I think I am experiencing this too.

> grab appears active but motion clamps

In _Helldivers 2_ (an over-the-shoulder shooter), the mouse only appears to work in menus, the moment I close them and enter gameplay the mouse refuses to rotate the screen at all. 

> invisible left/right rotation boundary

Experiencing exactly this on _Deep Rock Galactic._ (A first-person shooter)

> games that don't require continuous relative motion [work]

_Terraria_ and _Hollow Knight_ (side-scrolling games with no direct camera control) seem to work as expected, so that checks out. 

> Input: mouse only (controller unaffected)

This seems to line up with _Hollow Knight_ working properly on controller. Though I am noticing that a lot of games that would previously detect my controller are not anymore. _Hollow Knight_ seems to be the outlier.

**Comment by jstelzer** [comment]
Try launching Deep Rock with PROTON_ENABLE_WAYLAND=1  also try proton experimental/both options. Games launched outside of xwayland seem to not have the invible walls issue that happens in xwayland and for first person games it's a really blocker.

**Comment by silentTeee** [comment]
Okay, this is very strange: I am having completely different results today, even though I didn't see any updates from Steam or the COSMIC Store...

> Try launching Deep Rock with PROTON_ENABLE_WAYLAND=1

I added this launch option and got my full rotation back...but only when moving my mouse left 😕 moving it to the right, the "invisible boundary" still existed, which is really weird. As a sanity check I tried removing that launch option and surprisingly the behavior remained the same...

It's worth noting that entering an in-game menu eliminates the issue, but if I switch focus to another program and back to _Deep Rock Galactic,_ then the "invisible boundary" returns when moving my mouse to the right side.

> also try proton experimental

I always run Proton Experimental (save for one or two games that have issues with deprecated launchers)

Weirdly my issues with _Helldivers 2_ went away, despite me not changing anything in how I ran it...

I attempted playing both the above games multiple times across multiple power cycles of my machine today. 

I am baffled...

Edit to add: I had tried entering and exiting in-game menus yesterday and did not get this result, hence me being baffled.

**Comment by jstelzer** [comment]
I mean, it's not magic. Its a whole new compositor. The KDE folks have had  way more time to work around way more weirdness. The fact that it works this well this soon is frankly amazing. But yes, there's a few games I just relog and run under KDE for now. We'll get there.

**Comment by silentTeee** [comment]
Oh I wasn't complaining, I was merely lamenting my failure to offer consistent test results and be more helpful.

@jstelzer I appreciate the suggestions for workarounds!

**Comment by ids1024** [comment]
> Reproduces on COSMIC Wayland Borderlands4, Doom

Which Doom game(s) would that be? I guess I have Doom 2016 and Eternal (and some old Doom games) in my Steam library.

My home internet is a bit slow, so it takes a while to download modern games for testing.

Inconsistent issues are a pain to debug. If there's a simple test case that consistently reproduces it, it's probably not that hard to fix.

**Comment by ids1024** [comment]
https://github.com/pop-os/cosmic-comp/issues/1692 is another issue likely involving the same part of cosmic-comp, but different behavior and affecting different games.

That one I've seen, but then wasn't able to reproduce it when I wanted to investigate the issue...

**Comment by Hyperchaotic** [comment]
> [#1692](https://github.com/pop-os/cosmic-comp/issues/1692) is another issue likely involving the same part of cosmic-comp, but different behavior and affecting different games.
> 
> That one I've seen, but then wasn't able to reproduce it when I wanted to investigate the issue...

That one better describes the video I posted higher up, between 1 and 20 min into a GuildWars2 session. Annoyingly inconsistent to reproduce indeed. It only started happening for me recently but looks like others have seen it previously.

**Comment by skygrango** [comment]
> [#1692](https://github.com/pop-os/cosmic-comp/issues/1692) is another issue likely involving the same part of cosmic-comp, but different behavior and affecting different games.
> 
> That one I've seen, but then wasn't able to reproduce it when I wanted to investigate the issue...

In my case, this issue only occurs on proton xwayland game, and through a [PR](https://github.com/pop-os/cosmic-comp/pull/1861), I discovered that the window render geometry and input region are inconsistent, causing the error.

If you move the mouse within the constraint in the upper left corner, it will cause abnormal mouse movement.

since I now know this is related to mouse input, my personal solution is to stop trusting the mouse position reported by the window and instead directly record the last mouse position on the screen to force the setting. Now I can play the game normally. my temporary solution : [link](https://github.com/pop-os/cosmic-comp/pull/1861#issuecomment-3632382329)

By the way, FF14 can easily reproduce this mouse input error, but unfortunately it's not a free game. one phenomenon I observed is that if FF14 is not in full-screen mode, even though X11 considers its size to be 1600x900, the actual rendered area seen by the naked eye is still 3840x2160

**Comment by skygrango** [comment]
the [branch](https://github.com/skygrango/cosmic-comp/tree/temporary-fix-mouse-input) I used for research, and it's not cleaned up yet, but I'm sharing it with anyone who wants to play games with cosmic-comp to see if it helps

Note: I only tested it on a single monitor; the effect on multiple monitor is uncertain.

**Comment by skygrango** [comment]
monitor resolution: 3840x2160
client_scale: 2.0
same result occurs even with client_scale = 1.0

added the FFXIV recording for reference:

https://github.com/user-attachments/assets/4d8cb0e6-43e3-417f-8291-7622237b4fe4

**Comment by skygrango** [comment]
> monitor resolution: 3840x2160 client_scale: 2.0 same result occurs even with client_scale = 1.0
> 
> added the FFXIV recording for reference:
> 2025-12-19.18-55-03.mp4

Under the condition of floating layout, if I skip `workspace.floating_layer.map_internal` in `remap_unfullscreened_window`, the same error will no longer be reproduced. It appears there's something in map_internal that's disrupting the x11 window.

my idea was to respect x11 and skip all scaling steps first.

update [branch](https://github.com/skygrango/cosmic-comp/tree/temporary-fix-mouse-input)

src/shell/mod.rs
```diff
@@ -2450,6 +2470,7 @@ impl Shell {
         state: Option<FullscreenRestoreState>,
         loop_handle: &LoopHandle<'static, State>,
     ) -> CosmicMapped {
+        let is_x11 = surface.0.is_x11();
         let window = CosmicMapped::from(CosmicWindow::new(
             surface,
             loop_handle.clone(),
@@ -2525,12 +2546,18 @@ impl Shell {
                     },
                 ..
             }) => {
-                workspace.floating_layer.map_internal(
+                if is_x11 {
+                    workspace.floating_layer.space.map_element(window.clone(), Point::from((0, 0)), false);
+                    workspace.floating_layer.space.refresh();
+                }else{
+                    workspace.floating_layer.map_internal(
                     window.clone(),
                     Some(geometry.loc),
                     Some(geometry.size.as_logical()),
                     Some(fullscreen_geometry),
-                );
+                    );
+                }
```

https://github.com/user-attachments/assets/92ae06fd-4119-4165-aeda-23169d8946ef

**Comment by The1hauntedX** [comment]
I also ran into this behavior on RuneScape: Dragonwilds. No combination of DX11/12, Vulkan, Fullscreen, Fullscreen (windowed), or windowed worked. So that lead me down the xwayland/cosmic rabbit hole.
## Hardware
- GPU: NVIDIA GeForce RTX 3060 Ti
- Driver Version: `580.82.09` 
- 2 1920x1080 monitors

I'm curious about y'all's monitor setup. Unplugging my 2nd monitor, checking if the camera rotation issue was fixed (it worked!) and plugging the 2nd monitor back in while the game was still running resolved this issue for me and has worked after subsequent launches of the game, but I haven't checked to see if the "fix" persists after a restart - I'm done messing with it for tonight.  
Definitely curious to see if setting `PROTON_ENABLE_WAYLAND=1` works if the issue crops back up before resorting to @skygrango's patch

**Comment by Adam-Cosner** [comment]
For right now, the temporary fix seems to be to use Proton-GE and use the PROTON_ENABLE_WAYLAND=1 environment variable so that the apps run on Wayland.

**Comment by StripedMonkey** [comment]
I have started trying to switch over to Cosmic, and tried playing Arc Raiders today, initial playing worked but I was in game queuing and was sorting my application menu (dumping the billion LSP audio plugins into a folder so I never have to look at them again) while waiting. After opening an application and closing it, something (I couldn't tell what) was grabbing my mouse cursor attention, and I could not type in the browser, I could not open the application menu, and any dropdown menu would appear for a frame or less, before disappearing... relogging did fix the issue.

However, upon starting back up and joining a new game of Arc Raiders, the game was constrained to a ~90ish mouse move angle (this also applies to up and down). Although the game was successfully constraining the mouse pointer and the mouse was not going over the edge, it was not properly warping the pointer (or receiving mouse events once it reached the edge of the window). Restarting the game, switching x11 compat modes, etc. did not do anything to fix the issue. I have no idea what changed to cause this.

However, one thing that *shouldn't* have fixed it, but seemed to was when I messed around with my display settings and set the refresh rate to 144Hz (from 60), for both my monitors somehow fixed it.

**Comment by rdephillip** [comment]
So, I read through this and I've experienced the various mouse capture issues as well. I am trying to find some commonality, but I'm having an impossible time locating anything.

I have been able to reliably cause the problem though. After a restart basically every single game works fine. Once the mouse capture stops working, which I cannot find the exact trigger, it is broken in all Mouse capture camera games until session restart.

My test cases have been using Farming Simulator 25 and The Last Caretaker (DEMO). I just happen to have these handy. I've noticed the mouse capture issue is more commonly triggered with UE5 games, but I've seen the issues in UE5, Unity, Godot, Giants Engine, RAGE2 and RAGE3. Probably others that I'm not aware of. I haven't seen this issue in native games, but I don't think any of my native games use a relative mouse capture to control a camera.

The only thing I noticed in my journalctl -b 0 that was different was that when a games mouse was busted, I saw this in the logs after the game had initialized in steam and proton:
`cosmic-comp[2641]: [GL] GL_INVALID_VALUE error generated. Size and/or offset out of range.`

When I do some basic research on this this appears to be about the nVidia to Vulkan systems, but could also influence the mouse in some way? I don't know, the research was unclear.

If you would like to test this I can say that "The Last Caretaker (DEMO)" breaks the mouse for me 100% of the time. IT is doing the triggering offender reliably. In  the demo I get the ability to look until the cursor hits the border of the window.

It doesn't matter if this is Fullscreen, Borderless Window, or Windowed. Same results.

My control is Farming Simulator 25, but I've experienced the issue(s) in Satisfactory, SurrounDead, Way of the Hunter, Space Engineers, Space Engineers 2, MineMogul, Stationeers, and more where the relative camera to mouse is used.

My test:

1. Reboot for fresh session
2. Start Farming Simulator 25 (My control game)
3. Test mouse and verify it is working for full camera control
4. Close FS25
5. Open terminal and sudo journalctl -b 0
6. Observe if there are any errors
7. Close Terminal
8. Start The Last Caretaker (DEMO)
9. Test mouse and verify camera turns until mouse hits border of "window"
10. Close TLC
11. Repeat 5-7 and record any errors found
12. Start FS25 again
13. Test mouse and verify it now is "center locked" and the camera only moves slightly and immediately recenters
14. Close FS25
15. Repeat 5-7 and record any errors found
16. Reboot for fresh session
17. Start FS25
18. Test mouse and verify fully functional camera controls.

Notes:

PROTON_ENABLE_WAYLAND=1 on The Last Caretaker causes and Assertion Failed error. I didn't add the Vulkan bypass, or try this on FS25 when the mouse camera was not working.

I use `LD_PRELOAD="" gamemoderun %command%` with all proton games and I run Proton GE.

I do not have gamescope on this system as it never did anything useful for me when it was.

I have an nVidia 3090Ti, ASUS Z690-G Motherboard, and i9-12900K CPU.

These issues have been consistent problems in COSMIC since I loaded it in ALPHA 7 and my friend in Bazzite does not experience these issues, but does not have an identical setup or games to test with so take that for what it is worth.

After chatting with the Pop!_OS team on Mattermost it was considered plausible that cosmic-comp is the culprit as it happens across multiple games and engines that almost all work at some time or another. The Last Caretaker being the first one that never works for me properly.

UE games are the most common culprits in my experience. I do not know if it is UE5 exclusively or if UE4 titles also seem to have the issues.

I would be curious to find out how many of us are running multiple monitors rather than a single large monitor. I know that multiple monitors are supported, but it seems as though sometimes they are supported poorly.

**Comment by StripedMonkey** [comment]
I'm currently running two monitors. I will note that I also tried gamescope and it hung cosmic instantly to the point I had to restart, no ability to switch ttys or anything.

**Comment by mjhenkes** [comment]
I have this issue and am running a single monitor. The two games I tried (Arc Raiders and Abiotic Factor) are both UE 5 games.

I have since installed KDE-plasma and have been running games from that DE instead of COSMIC with no mouse issues.

**Comment by beforethesurge** [comment]
Not 100% if this will solve this for everyone, but I've had a similar issue where when playing the following games, I would be unable to look around at all (mouse seems to be locked to the middle of the screen too tightly) or my mouse sensitivity would be INSANE

- Sea of Thieves: Mouse is on crack
- Jump Space: Mouse locked to center view (can still move around with WASD and navigate menus with mouse, but can't look around) 

The fix I found that fixed both of these is with the `X11 Applications Compatibility` menu

<img width="863" height="741" alt="Image" src="https://github.com/user-attachments/assets/046a6aa1-c453-4170-8280-5cd90f8b466d" />

Having the following options setup seems to work well for me (even fixed an issue when ALT-Tabbing would soft-lock my controls (can't move or look in-game))

I'd have to take some extra time to really see what setting in here fixes it, but I'd imagine it's something to do with the key-tracking, as the mouse option didn't seem to change anything, but could very well be the window settings

More of a workaround than probably a fix but, it gets the games to work on my end

**Comment by StripedMonkey** [comment]
Like I mentioned before,
> Restarting the game, switching x11 compat modes, etc. did not do anything to fix the issue. I have no idea what changed to cause this.

The compatibility modes don't seem to have changed much for me. Currently I am on "Maximum compatibility mode" and "no keys" and it is working for me. It randomly started working after I changed my refresh rate.

**Comment by rdephillip** [comment]
@StripedMonkey 

> It randomly started working after I changed my refresh rate.

Interestingly enough, I decided to give this weirdness a try. My monitors 1, 2, 3 were all 165hz and my 4th is a drawing monitor locked at 60hz.

I play on DP_1 so I dropped my three 165Hz down to 144Hz in COSMIC Settings and The Last Caretaker worked beautifully. I wonder if this is a hint at some limitation the cosmic-comp is running into.

I'll keep playing/testing various games that I know the issue happens in and see if it returns. If not... that's a very strange workaround.

**Comment by rdephillip** [comment]
Spoke too soon. Before rebooting I'm going to try to jiggle the monitor refresh rates again to see if it resolves without a reboot. I'm doubtful, but worth a shot.

**Comment by beforethesurge** [comment]
Found that my fix earlier with X11 compatibility didn't seem to work as I'm having the issue again (must have gotten lucky for a bit)

https://github.com/pop-os/cosmic-epoch/issues/2021

Seems workaround consistently seems to be logging out and back in

**Comment by rdephillip** [comment]
Yes, the only surefire workaround right now is to take an action to fully restart the cosmic-comp by restarting. I don't think logging out and logging back in worked for me, but I'm willing to try that next time it shows up.

**Comment by rdephillip** [comment]
New information that might be helpful-ish... if this is being reviewed for resolution:

I was in Farming Simulator 25, playing just fine. I had to alt+tab, not the first time.

While alt+tabbed I opened my steam wishlist to look at a game for a friend and paused Spotify.

In that time the error:
`cosmic-comp[2607]: [GL] GL_INVALID_VALUE error generated. Size and/or offset out of range.`

Showed up, and when returned to FS25 I couldn't look around anymore. First time it ever happened mid-play. Further evidence that there is something in the cosmic-comp to me at least.

**Comment by skygrango** [comment]
> For right now, the temporary fix seems to be to use Proton-GE and use the PROTON_ENABLE_WAYLAND=1 environment variable so that the apps run on Wayland.

patch https://github.com/pop-os/cosmic-comp/pull/1928 and switch to wayland work for me.

I saw a fix for the cursor position issue in xwayland upstream, but I'm not sure if it's entirely related to the incorrect cursor position I observed : https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/2113

**Comment by UKWolfy** [comment]
I’m also affected by this fullscreen XWayland input issue on COSMIC (Wayland) with Proton/Unity games like Terra Invicta.

Specifically:
Mouse click-and-drag camera control doesn’t work reliably — it may work once then stop capturing input entirely.
Keyboard movement works fine, but relative mouse input does not register once the issue occurs.
I’ve tested disabling Steam overlay, enabling COSMIC’s X11 mouse button events, and trying windowed-fullscreen launch flags, but the problem persists.
This appears to be similar to other reports of mouse relative/input breakdown in 3D games on COSMIC, indicating a compositor/XWayland input problem that affects game view control.
In my case, the issue is reproducible on Pop!_OS 24.04 with COSMIC. Switching to an X11 desktop (e.g., XFCE) temporarily resolves the mouse capture, but within COSMIC the behavior remains broken despite workarounds.
This input capture bug significantly impacts playability for games that rely on relative mouse movement.


Edit: Tried fix above from @skygrango 
Worked for Terra Invicta.

Proton-GE
PROTON_ENABLE_WAYLAND=1 gamemoderun %command%

**Comment by benfrussell** [comment]
Experiencing the same issue as of the most recent update. 

PROTON_ENABLE_WAYLAND=1 or changes to the X11 compatibility settings tweaks have not resolved it in the games I've tried.

**Comment by chrisglass** [comment]
Still affected by this - my current game reproducing this is "Helldivers 2", where: the mouse movement to move the in-game camera (in 3d) doesn't work, however the mouse works perfectly fine in the game's menu (2d).

**Comment by duplexsystem** [comment]
I also have this issue. Nothing has helped. Seems to be somewhat random.

**Comment by rdephillip** [comment]
I will say that something has changed slightly in the recent updates, but it is still a present issue. It is not as likely to happen as it did several weeks ago.

Things I've noticed:
* If you have a browser open playing a video it seems to happen more frequently. Perhaps this is only if the browser is using GPU acceleration?
* If you start the game but are interacting with other windows while it is loading up it is more likely to happen.
* If Discord is focused during game startup it seems to happen more often. Perhaps this is also a GPU Acceleration related thing?
* You only have to log out and log back in to restart the compositor to fix the issue... most of the time. Not Lock, but Log Out. Sometimes you have to do a full restart, I don't know why.
* I've not captured any newer logs that provide evidence beyond the compositor failure I've already posted about before.
* PROTON_ENABLE_WAYLAND=1 may work on some games, but it appears that UE5 games will often not launch with this.
* Proton GE has also received at least 2 updates since I last posted here up to 10-29, and seems to be more reliable, but COSMIC has also received several large system updates in the same time period. (none specifically to the cosmic-comp, but it isn't always easy to tell)

I can say that opening a game with less windows open to "steal focus" seems to be more reliable. Once the games are open you can just tab out and open whatever you need. I've only had one instance where the mouse-capture failed AFTER the game had been running and I've been unable to replicate that specific issue.

**Comment by Hyperchaotic** [comment]
Hit invisible wall today in Enshrouded. It seemed to me the turning of my character was blocked/invis wall appeared at the time when a visible mouse would otherwise have hit the side of the screen.  I wonder if the mouse is restricted by screen boundaries even when invisible?

**Comment by silentTeee** [comment]
That actually seemed to be the case, from my initial observations: for games with the invisible boundary, if I switched into a game menu and moved my mouse all the way to one edge of the screen, then switched back into gameplay, I couldn't move the camera any further towards that edge of the screen.

**Comment by tim77** [comment]
Same here with The Elder Scrolls IV: Oblivion Remastered. Games uses Unreal Engine 5. Borderless window mode by default. I've tried all window modes and issue still persist. 

- COSMIC DE: `1.0.4`
- mesa: `25.3.4`
- amdgpu
- radv
- Fractional scaling: `x1.25`
- Display refresh rate: `180Hz`

**Comment by duplexsystem** [comment]
Space Engineers and SE2 have a weird manifestation of this issue where the mouse is super accelerated and you can only move in a circle looking up

**Comment by jx7n** [comment]
> Space Engineers and SE2 have a weird manifestation of this issue where the mouse is super accelerated and you can only move in a circle looking up

I also experienced this in Resident Evil 5 and (only recently) Overwatch 2

**Comment by markvdkooij** [comment]
For what it's worth, I've had this issue in multiple games, primarily in Guild Wars 1 and World of Warcraft. What I've noticed is that every first boot of the day the issue is there. But specifically after I log out of my user, and then log right back in, the issue is resolved. Works every time. So not a reboot, a relog.

I am as of writing on the latest version of Pop!_Os Cosmic 24.04 LTS.

Update: I've noticed that after a relog the issue suddenly came back. I was in-game where everything was working, and all of a sudden not anymore. So something happens during usage of the OS that triggers this issue. I can't figure out what exactly.

**Comment by flummydummy** [comment]
I want to add a seemingly related issue, where the mouse suddenly jumps to the upper left corner of the screen when dragging and moving sliders in games, which makes it very difficult to make adjustments. For example, audio sliders in most games I've played, or "split item" sliders in Baldur's Gate 3 and similar sliders in other games.

Also, something similar happens when hovering the mouse over text fields in games. E.g. in Total Conflict: Resistance, where renaming battalions or settlements is impossible with this bug. As soon as the mouse touches the text input field, it jumps to the upper left corner of the screen.

**Comment by addy419** [comment]
Same in Palworld. I seem to be hitting a wall when looking back. It was working a few months ago

**Comment by toast288** [comment]
Adding an observation that may help narrow down the root cause — this appears to be a bidirectional focus-change issue with pointer constraints.

**Environment:** Pop!_OS COSMIC, Corsair Scimitar Pro RGB mouse, Overwatch via Proton/XWayland

**Symptom 1 (in-game):** Intermittently, the mouse cursor becomes visible during gameplay and the camera snaps to the ceiling — consistent with absolute coordinates leaking instead of relative deltas. Alt-tabbing sometimes resolves it, but not consistently. Restarting the game reliably fixes it.

**Symptom 2 (alt-tabbed out):** After alt-tabbing out of the game with other windows overlapping it, the cursor initially works normally on the overlapping windows. However, if the cursor passes over the game's window region, the cursor icon changes to the game's cursor — indicating the game is recapturing pointer input despite not being focused. After this, the cursor becomes confined to the game's input region: you can trace the borders of the overlapping windows but can't click into them.

**Conclusion:** This suggests cosmic-comp's pointer constraint state isn't being properly toggled on focus changes. The confinement fails to fully engage on focus-in (causing the ceiling/absolute coords issue) and fails to fully release on focus-out (causing the cursor trap when alt-tabbed). Likely the same underlying state machine bug in both directions.

**Comment by StripedMonkey** [comment]
I have two more examples of where the "underlying state machine" may be inconsistent, the first is one that I recorded a while ago, but did not put in an issue for:

1. When launching Arc Raiders, I did something that caused the game to drop out of fullscreen when opening the application drop down, and instead it only took up part of the screen. Somehow, the pointer position became desynced from the pointer position that was reported to the game note that it also appears that the pointer position appears to diverge further to the left as I approach the right side of the screen (perhaps it is scaling to my 1080p monitor?):

https://github.com/user-attachments/assets/96325b3f-6109-4520-8a2e-4a174d00d676

2. When dropping into a game of Arc Raiders, the cursor warping seems to jump all over the place, and the game is completely unplayable. Moving the mouse while the cursor is supposed to be locked to the game is a a migraine inducing glitch fest: 

https://github.com/user-attachments/assets/11f15764-710c-4f40-9248-58fb0be5f8cf

 It's hard to reliably reproduce these issues, but they always seem to happen when I alt tab out of the game when it is starting up, or loading things.

**Comment by skygrango** [comment]
While most games can be played normally using Wayland mode, some games(like ff14) seem unable to be played normally using Wayland

To debug the cursor's behavior on xwayland, I wrote a Wayland layer and added a mechanism for sharing mouse coordinates in cosmic-comp to display the cursor.

I also applied the current pointer constraint patch #1861  for testing.

FF14 seems that clicking the mouse in the upper left of the game causes abnormal jumping behavior, which is likely related to surface detection problem.
https://github.com/user-attachments/assets/4b4ddbbc-2bb5-4a66-86e6-4d846815c64b

Clair Obscur: Expedition 33: after closing the menu, the cursor should theoretically be in a pointer lock state. However, it may sometimes unexpectedly exit this state.

https://github.com/user-attachments/assets/1f83353e-26dc-4376-b252-97b873357140


update: After adding more state tracking, the locked and confined states in Clair Obscur: Expedition 33 look normal, but it's strange that the cursor can still move even when locked.

https://github.com/user-attachments/assets/27c9d46e-e5f2-4f67-9329-5266f7337b46

**Comment by symba98** [comment]
for what it's worth, the issue seems to be relieved for a period when disconnecting my second monitor and connecting it back again.

**Comment by attusan** [comment]
Reproduced with Elder Scrolls Online under Proton. Camera spins wildly in COSMIC session but behaves normally in GNOME on X.org.

UPDATE 4/14/26:

This problem is still occuring. Logging out and logging back in again seems to resolve it.

UPDATE 3/15/26:

Reproduced again in COSMIC session with ESO under Proton. This time the issue appeared after leaving the game idle for a few minutes with the in-game map open. Once it started, restarting ESO did not fix it, but logging out of the COSMIC session and logging back in did clear it.

This suggests the problem is tied to session/compositor input state rather than the game process itself. libinput debug-events continued to show generally plausible mouse motion while the issue was occurring, so this does not look like a simple hardware or raw libinput failure. It appears more likely that relative pointer / mouse capture state becomes corrupted in the COSMIC/Wayland/XWayland stack, and that bad state persists until the session is reset.

Additional notes:

- ESO behaves normally for me in GNOME on X.org
- The mouse is using a Logitech USB receiver, not Bluetooth
- Disabling Bluetooth did not produce any clear change
- The issue seems easier to trigger after idle / no input time

UPDATE 3/13/26:

Observed erratic camera rotation in ESO under COSMIC Wayland with a Logitech M720 Triathlon (via Logitech USB receiver). Switching to GNOME on Xorg avoided the issue. The problem disappeared after a 3/11/26 apt upgrade (GTK4 + NetworkManager packages). Solaar was installed the day before, so the root cause is unclear.

**Comment by MikkelVibe** [comment]
I also had the same issue when playing sorroundead. I gave up trying to solve it and just plugged in my controller, but when I did all of a sudden my mouse worked perfectly again and as long as my controller is on it works.

**Comment by chrisglass** [comment]
I think I debugged the issue successfully.

It seems like the relative pointer state was getting dropped when entering pointer capture state in COSMIC comp.

The fix lives in my branch: https://github.com/chrisglass/cosmic-comp/tree/global-pointer-protocol-state

I can now play helldivers2 properly on COSMIC and testing with my other favorite games seem successful as well, but I would appreciate more testing from people in this thread before I submit the PR (in particular, I'm not sure I understand all possible side effects of my change since it's the first time I touch the cosmic-comp codebase).

To test, please checkout my branch then "make; make install". No guarantees this will not explode in some unexpected way :)

**Comment by hexxacubic** [comment]
I have the same issue with Enshrouded on Pop! OS 24.04 LTS with Cosmic_DE.
I tried `PROTON_ENABLE_WAYLAND=1 %command% -force-grab-cursor` but it doesn't work. 

UPDATE: Now the bug is gone after a reboot, so maybe the command works.

**Comment by BlakeGardner** [comment]
> I have the same issue with Enshrouded on Pop! OS 24.04 LTS with Cosmic_DE. I tried `PROTON_ENABLE_WAYLAND=1 %command% -force-grab-cursor` but it doesn't work.
> 
> UPDATE: Now the bug is gone after a reboot, so maybe the command works.

Rebooting or logging out and back in always fixes it for me, but then it randomly reoccurs. The only pattern I’ve noticed is that the longer I use COSMIC before launching a game, the more likely the bug is to show up. If I boot up and immediately start gaming, it seems less likely.

**Comment by Adam-Cosner** [comment]
Not 100% sure about it, but it seems that this issue only happens for me after waking from suspend

**Comment by hexxacubic** [comment]
> > I have the same issue with Enshrouded on Pop! OS 24.04 LTS with Cosmic_DE. I tried `PROTON_ENABLE_WAYLAND=1 %command% -force-grab-cursor` but it doesn't work.
> > 
> > UPDATE: Now the bug is gone after a reboot, so maybe the command works.
> 
> Rebooting or logging out and back in always fixes it for me, but then it randomly reoccurs. The only pattern I’ve noticed is that the longer I use COSMIC before launching a game, the more likely the bug is to show up. If I boot up and immediately start gaming, it seems less likely.

Pop! OS was my first Desktop Linux, I used it for more than 1 year but the 'upgrade' to 24.04 LTS is a disaster. That's not an operating system, it's a meme. Nothing works. RAM memory leaks, VRAM memory leaks, GUI glitches, Cursor and camera bugs in games, Pipewire and ALSA are broken, my audio interface is falsely detected as a surround system and there is no sound. Pop! OS 24.04 LTS is a joke.

Windows fucked up my system multiple times and now Linux...
This has to stop. I'm going to switch to Fedora KDE. 😢☹️
Thumbs down, System 76. 👎

**Comment by Android789515** [comment]
Hallelujah, `PROTON_ENABLE_WAYLAND=1` was able to get gamescope to capture my cursor!

**Comment by Milli189** [comment]
this is happening to minecraft as well, when opening the inventory the cursor is never in the middle where it's supposed to be, but it's always somewhere else

**Comment by barryfl** [comment]
I would say this is related to the issue that I posted (https://github.com/pop-os/cosmic-epoch/issues/3417), 

You can temporarily fix the issue by running the game or steam itself in x11 with environment variables, but when the surfaces that COMSIC tracks gets out of what that fix will fail until a reboot (you can also generally work around it by running gamescope and using that to force mouse capture but that can cause significant performance hits from what I've seen as well as keep you from using your mouse for anything else while playing the game)

Edit: added complete link to issue i mentioned instead of just the issue number.

**Comment by prgmatic** [comment]
Same deal here. Issue resolves after a reboot.

**Comment by Android789515** [comment]
And just like that, after a system update, `PROTON_ENABLE_WAYLAND=1` no longer works for me. I can't play any games involving a camera anymore because I upgraded my system. Wtf, System76?

**Comment by Milli189** [comment]
> And just like that, after a system update, `PROTON_ENABLE_WAYLAND=1` no longer works for me. I can't play any games involving a camera anymore because I upgraded my system. Wtf, System76?

the latest updates are introducing so many bugs it's insane, and they also closed my issue unjustly and don't want to reopen it https://github.com/pop-os/libcosmic/issues/1260

**Comment by barryfl** [comment]
I appreciate that the idea this an Xwayland issue, but as near as I can tell this is a COSMIC issue (which is why I listed the issue I did above).  My assertion for why a lot of this is COSMIC related that the OS i have installed on my other drive for testing right now (in a bid to be my primary OS) is kubuntu 26.04 which is Plasma (Wayland) and I have none of the need to do all the config dancing that I do in Pop to make things run, I don't have the recurring surface issue that I posted the bug for which is resolved by reboot etc.

Not saying that there *aren't* Wayland issues that are potentially separate from COSMIC but side by side Plasma and COSMIC the issues I'v ebeen referencing *only* happen in COSMIC.

**Comment by skygrango** [comment]
For those who really want to play games on the Cosmic

I reimplemented the pointer-constraints functionality on top of the latest commit and adjusted its behavior.

Note that the code hasn’t been cleaned up yet and I’m still looking for additional bugs, so use it with caution. Please use with  `PROTON_ENABLE_WAYLAND=1` (Make sure your Proton version support this)

I tested this with Crimson Desert, Gray Zone Warfare, and Clair Obscur: Expedition 33, and it works well for me. If anyone wants to try gaming on cosmic-comp (I recently encountered some problems while playing games using KDE, so I switched back), feel free to use it.

- the pointer constraint is released on window focus change 
- in confined mode the cursor is no longer forcibly blocked at boundaries—instead, its position is clamped to the nearest valid x/y coordinates to prevent it from sticking to edges

repo link: https://github.com/skygrango/cosmic-comp/tree/unstable-implement-pointer-constraints-v2

**Comment by skygrango** [comment]
> For those who really want to play games on the Cosmic
> 

update: https://github.com/skygrango/cosmic-comp/tree/unstable-implement-pointer-constraints-v6

Games that I have been tested and confirmed to be playable with Proton cachyos-10.0-20260428-slr:
- Crimson Desert (Wayland)
- Gray Zone Warfare (Wayland)
- Clair Obscur: Expedition 33 (Xwayland)
- Minecraft (Native)
- HELLDIVERS 2 (Xwayland)
- R.E.P.O (Wayland)
- Final Fantasy XIV (Xwayland)
- ARC Raiders (Wayland)

**Comment by rdephillip** [comment]
The most reliable tweak so far for me has been to apply the launch options:

`PROTON_WAYLAND_MONITOR=DP-1 PROTON_ENABLE_WAYLAND=1 LD_PRELOAD="" gamemoderun %command%`

_Note: Set the Monitor to your preferred default monitor. DP-1 is just my primary monitor._

I have not had the opportunity to provide extensive testing to see if the specific issue shows up, but I've been able to reliably launch games with first and third person cameras controlled by the mouse. As my time has been more limited, I'm not certain if this is due to me only playing on "clean restarts" or not, I apologize. I wish I could offer more extensive information.

I do not believe I've encountered any games that could not be played, some just have this issue... sometimes.

If I find time to do more extensive testing, I will be happy to provide further information.

**Comment by skygrango** [comment]
update: https://github.com/skygrango/cosmic-comp/tree/gaming

This includes a fix for smithay's relative pointer problem: [PR](https://github.com/Smithay/smithay/pull/2023)

I hope this will resolve the mouse freezing issue in first or third-person games in Xwayland mode.

We will see

**Comment by skygrango** [comment]
update: https://github.com/skygrango/cosmic-comp/tree/gaming-v3

I think it should be like KDE now, I need to wait for smithay's update, so I'm providing this for you to try first.

**Comment by josip-k** [comment]
@skygrango i have tried your branch, and i can confirm that the mouse cursor is now working in Hell Let Loose, whereas before trying it it didn't work at all - game completely ignored all mouse inputs.

**Comment by skygrango** [comment]
> [@skygrango](https://github.com/skygrango) i have tried your branch, and i can confirm that the mouse cursor is now working in Hell Let Loose, whereas before trying it it didn't work at all - game completely ignored all mouse inputs.

Congrats! I have already submitted it for review: https://github.com/pop-os/cosmic-comp/pull/2357

Let's enjoy playing games!

**Comment by BlakeGardner** [comment]
This issue and associated PR that was just merged has comments suggesting the mouse issue was fixed along with the full screen issue initially reported. I've not been able to confirm yet since the mouse capture issue is intermittent for me. https://github.com/pop-os/cosmic-epoch/issues/3495

**Comment by josip-k** [comment]
@BlakeGardner I can confirm that the mouse issue is still present in Hell let loose. It is better now, the game is fullscreen, but the mouse is very inconsistent, if you make the game windowed with Alt + Enter, only then the mouse can be used in game.

**Comment by noahtallen** [comment]
Some extra data: I originally experienced the issue in Subnautica 2. For this game, I was able to confirm that a cosmic-comp downgrade solved it, and for me mouse capture was also fixed in the latest cosmic-comp version. (I'm on CachyOS.)

But in my case, downgrading to a very recent version (e.g. a version that came out _after_ this issue was open) also fixed it, so it sounds like multiple bugs? 🤔

**Comment by skygrango** [comment]
> Some extra data: I originally experienced the issue in Subnautica 2. For this game, I was able to confirm that a cosmic-comp downgrade solved it, and for me mouse capture was also fixed in the latest cosmic-comp version. (I'm on CachyOS.)
> 
> But in my case, downgrading to a very recent version (e.g. a version that came out _after_ this issue was open) also fixed it, so it sounds like multiple bugs? 🤔

`pointer-constraint-v1` protocol can provide correct cursor behavior in games and theoretically avoid the "hitting a wall" phenomenon. https://github.com/pop-os/cosmic-comp/pull/2357 is needed.

However, as I understand it, there seems to be a chance of an error in x11's handling of window(especially when you frequently switch the focus of window), causing the x11 window to become unable to receive mouse-relative event input after the cursor position is locked(just describing the phenomenon, I actually checked, and the mouse-relative events were indeed received by x11, but were completely ignored). the only solution is to log out and log back in. I don't yet know which x11 implementation is causing the problem, so even after #2357 is merged, if the same xwayland issue persists, I still recommend using `PROTON_ENABLE_WAYLAND=1` first.

**Comment by WatchMkr** [comment]
The pointer constraints protocol was tagged for release yesterday. CachyOS is usually pretty fast to pick up new tags. It was released to Pop a couple days ago.

**Comment by BlakeGardner** [comment]
After updating to the latest Pop OS, this issue has been fixed for me. I am able to free-look with the camera in my game without it hitting the invisible wall.

**Comment by flummydummy** [comment]
Not fixed for me on Fedora 44 (cosmic-comp version 1.0.15). Tested so far in Half Sword Demo and Arma Reforger. In the former, my mouse hits the invisible wall. In the latter, the game doesn't register any mouse movement at all.

Edit: Same issue in Baldur's Gate 3 and Alchemy Factory.

**Comment by Guicapau-PT** [comment]
> Not fixed for me on Fedora 44 (cosmic-comp version 1.0.15). Tested so far in Half Sword Demo and Arma Reforger. In the former, my mouse hits the invisible wall. In the latter, the game doesn't register any mouse movement at all.
> 
> Edit: Same issue in Baldur's Gate 3 and Alchemy Factory.

Same using CachyOS COSMIC 1.0.15 tested on Outlast Trials but I dont know if 1.0.16 fixed this as its not on the Arch repos yet maybe someone can confirm it?

**Comment by mayabkb-ux** [comment]
This problem still persists for me. When playing "Paralives" or "Librarian" , I can’t tilt or rotate the camera with the mouse—it’s like hitting an invisible wall.

The interesting part is this: it only happens if I start a browser before launching the game. If I boot my PC and start the game directly, everything works fine and I can tilt and rotate the camera normally. It doesn't matter with browser. 

My setup:
- two monitors
- Pop!_OS 24.04
- COSMIC with Wayland
- NVIDIA GeForce RTX 3060

What I’ve tried:
- different Proton versions including GE
- launch option 'PROTON_ENABLE_WAYLAND=1'
- windowed mode and fullscreen
- different key combinations with Super

_I'm sorry if I made mistakes. Englisch isn't my mother tongue._

**Comment by Laarikin** [comment]
Experiencing this issue on Fedora 44 COSMIC spin as well. Been happening on an off ever since I started using COSMIC some months ago.

**Specifications:**
- Fedora 44 COSMIC (1.1.0) spin
- **CPU:** Ryzen 9 7950X
- **GPU:** RX 7900XT
- **RAM:** 32GB

**Comment by lilbropeep** [comment]
I have been experiencing this on CachyOS for at least the last month, both on Satisfactory and Cyberpunk. It's a bit annoying, but Cosmic is so great that I spent some time this evening testing in the hope that I could help get this resolved. 

Testing setup: dual monitors with 1440p resolution, launching the game full screen on right monitor. Running Cyberpunk through Steam. cosmic-comp 1:1.2.0-1.1.

### Repro steps:

Example A: in-game character stops turning left after a certain point.
1) Suspend your PC with a Firefox window open in the first workspace of the left monitor. 
2) Resume PC.
3) Load game.
4) Proceed past the menu into the game itself.
4) Observe that you cannot turn left beyond a certain point. Observe that the mouse shows up on the far left of my left monitor sometimes, if it feels like it.

Example B: in-game character won't turn at all in-game (inconsistent)
1) Suspend your PC with a Firefox window open on the bottom screen of the first monitor.
2) Resume PC.
3) Load game.
4) Sometime during this process, move the workspace the Firefox window is in from the bottom of your list (I had 3 left monitor workspaces open) to the top. Alt tab and super + arrows a few times if you feel like it.
5) Observe that once you load into the game, the mouse won't register at all except in the shell menu.

Note that there seem to be several variables that affect exactly how this bug is expressed on my machine. Sometimes example B repro steps lead to example A behaviour. Example B behaviour has been hard to replicate, and I think it requires some alt tabbing or other more general digital hooliganism in the middle of the process.

### Workarounds:

Example A above
1) I could close the game, quit Firefox, then start the game again. Fixed.
2) I could close the game, move the Firefox window down a workspace. Fixed.

Example B above
1) I could press super + F11 to go to windowed mode, then super + F11 to go back to fullscreen. Fixed. This didn't work for Example A  all the time, except sometimes it did, maybe when example B expressed as example A. I don't know.

### Situations where it does not occur

1) On a fresh boot/restart. It doesn't seem to matter whether Firefox is loaded before the game or not. 
2) It seems like once you fix it it's gone until the next suspend.

Hope that helps!

**Comment by weelillad** [comment]
Another workaround that sometimes works for me, is to switch the game between monitors using super + alt + shift + arrow keys
