### ISSUE TITLE
Windows spawning with dimensions larger than host display.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-comp#246]
Both horizontally and vertically, I can spawn an application window that overhangs the bounds of its host display. I used Firefox for this, which remember its previous size and screen position. Here's how I noticed it:

With a dual-head set up (1920*1080 + 1366*768) I launched Firefox on the 1080p display, and expand it. Then I closed Firefox. Later, I launched it on the 1366*768 display, causing overhang. Because the window was centred, I had to fall back on keyboard short cuts to resize. 

I recreated the issue in this screenshot, showing only vertical overhang on the browser window on the bottom display:

![Screenshot_2023-12-15_16-55-53](https://github.com/pop-os/cosmic-comp/assets/98765732/5c9b7671-770d-403a-b1ae-dd7231dffb20)

**Comment by Drakulix** [comment]
Firefox remembering the last size is a problematic case, because it will ignore what the compositor sends as a size, when restoring.

Can you reproduce this with any other client?

**Comment by WatchMkr** [comment]
Let's take a look at what GNOME is doing. They're handling this situation with Firefox somehow.

**Comment by XV-02** [comment]
> Firefox remembering the last size is a problematic case, because it will ignore what the compositor sends as a size, when restoring.
> 
> Can you reproduce this with any other client?

With regards to other clients - not yet. I haven't dived deeply into the issue though. I can start looking at other clients and see if anything obviously has issues. 

> Let's take a look at what GNOME is doing. They're handling this situation with Firefox somehow.

On Pop with Gnome, I was seeing the window getting re-sized to the dimensions of the display with the smallest available screen real-estate. 

So, if I initially created a large window on a 1080p display, then closed and relaunched Firefox, the window would re-size at launch to the available real-estate of the 1366*768 display - that is the screen area which was not encumbered by the dock or the top-bar. This seemed to happen shortly after the window was launched. This might be because of the fix mmstick mentioned of fixing windows size in that first second.

**Comment by XV-02** [comment]
I have not been able to trigger this issue with any application other that Firefox. I also don't know for certain of any other applications that remember their placement/size the way Firefox does. I'm inclined to call this a Firefox issue, and to believe that - with the likelihood of such disparate screen set-up being small and the plan to introduce `Super + click` interactions - we should be okay for at least the alpha with this as it currently is.

**Comment by WatchMkr** [comment]
> with the likelihood of such disparate screen set-up being small and the plan to introduce Super + click interactions

This config actually describes my home and work setup. It's common that a laptop is plugged into a higher-resolution external. We should fix this for the alpha.

**Comment by Lcstyle** [comment]
This is still reproducible — floating windows that are sized for a larger display overflow the bounds when they land on a smaller one, both on initial spawn and when dragged cross-monitor.

I've implemented a fix that clamps floating window dimensions to the target output in two places:

1. **On spawn** (`map_internal`): clamp the initial floating size to the target output bounds before placement — [`073c80e6`](https://github.com/Lcstyle/cosmic-comp/commit/073c80e6)
2. **On cross-monitor drop** (`move_element`): clamp floating window size to the destination output when a window is dragged between monitors of different resolutions — [`f4e7b562`](https://github.com/Lcstyle/cosmic-comp/commit/f4e7b562)

Both on branch [`integrated-features`](https://github.com/Lcstyle/cosmic-comp/tree/integrated-features).
