### ISSUE TITLE
Duplicate mouse cursor upon login from GDM

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#34]
After logging in from GDM, my mouse cursor from GDM remains on the screen in the position it was at in GDM for about ten seconds, while I get a new mouse cursor to actually use in COSMIC.

https://user-images.githubusercontent.com/7199422/186207865-21f7409e-4b00-42d1-bfc1-d4ab154b9aa8.mp4

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/352c526e9e2be28b093bde75764c97ba536226cb !
Please re-open, if you if encounter it again once that commit is packaged.

**Comment by sparkwj** [comment]
issue not fixed

https://github.com/pop-os/cosmic-comp/assets/5135832/deb6fc06-3d85-4510-975c-fc1073d598c3
