### ISSUE TITLE
Cosmic Desktop/OS freeze on Application Startup

### ISSUE THREAD

**Issue by MattiBRNDMR** [pop-os/cosmic-comp#627]
NVIDIA Driver Version: 555.58.02
CPU: Intel i7-7700HQ (8) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1070 Mobile
popdev:master repo added

Hi everyone, 
while testing cosmic on my laptop, I tried to give the 3D Application "Houdini" a shot. Up until a couple of days ago, Houdini would start but eventually crash after 10-20 seconds of use. As of recently, the whole Desktop/OS would freeze as soon as Houdinis UI loaded up. Only a hard power-off would get me out of this. On POP-gnome-x11 and POP-gnome-wayland however, houdini runs flawlessly. 

Running houdini via terminal on POP-gnome-wayland says:

`matti@pop-os:~$ Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` - then it starts and runs without any issues on POP-gnome-wayland

starting on cosmic before everythings freezes it says:

`matti@pop-os:~$ qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`

tried to force `QT_QPA_PLATFORM=wayland houdinifx` to run but then it says:

`matti@pop-os:~$ QT_QPA_PLATFORM=wayland hindie
Qt Error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, webgl, xcb.`

forcing `QT_QPA_PLATFORM=xcb houdinifx` for instance, results in no terminal errors, but the same desktop/os freeze occurs.

Journalctl output for cosmic-comp:

Jul 18 12:18:49 pop-os cosmic-comp[2270]: Failed to read config 'workspaces'
Jul 18 12:18:49 pop-os cosmic-comp[2270]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jul 18 12:18:49 pop-os cosmic-comp[2270]: Key-Binding 'Period' only matched case insensitive for "period"
Jul 18 12:18:49 pop-os cosmic-comp[2270]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jul 18 12:18:49 pop-os cosmic-comp[2270]: Key-Binding 'Period' only matched case insensitive for "period"
Jul 18 12:18:49 pop-os cosmic-comp[2270]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jul 18 12:18:49 pop-os cosmic-comp[2270]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jul 18 12:18:50 pop-os cosmic-comp[2270]: Unable to become drm master, assuming unprivileged mode
Jul 18 12:18:50 pop-os cosmic-comp[2270]: Unable to become drm master, assuming unprivileged 

Let me know if you need anything and thank you in advance!

**Comment by Drakulix** [comment]
> matti@pop-os:~$ qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

You are probably missing the required qt-subpackage. I don't know which distro you are on, but it is usually named something like `qt5-wayland`.

> forcing QT_QPA_PLATFORM=xcb houdinifx for instance, results in no terminal errors, but the same desktop/os freeze occurs.

That obviously shouldn't happen, thanks for the report, will investigate.

**Comment by MattiBRNDMR** [comment]
> > matti@pop-os:~$ qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
> 
> You are probably missing the required qt-subpackage. ~I don't know which distro you are on, but~ On Pop!_OS it is named `qt6-wayland`.
> 
> > forcing QT_QPA_PLATFORM=xcb houdinifx for instance, results in no terminal errors, but the same desktop/os freeze occurs.
> 
> That obviously shouldn't happen, thanks for the report, will investigate.

Thank you for the fast reply & investigation! The current version of Houdini still uses qt5.15 - so I guess the package I would need is "qtwayland5"? Seems like POP ships with qt5 only by default, as there are only qt5 libraries to be found under `/usr/lib/x86_64-linux-gnu/`

**Comment by Drakulix** [comment]
> "qtwayland5"

yes, that sounds right.

**Comment by MattiBRNDMR** [comment]
> > matti@pop-os:~$ qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
> 
> You are probably missing the required qt-subpackage. ~I don't know which distro you are on, but~ On Pop!_OS it is named `qt6-wayland`.
> 
> > forcing QT_QPA_PLATFORM=xcb houdinifx for instance, results in no terminal errors, but the same desktop/os freeze occurs.
> 
> That obviously shouldn't happen, thanks for the report, will investigate.

installing `qtwayland5` fixes the warning I got starting houdini on POP-gnome-wayland `matti@pop-os:~$ Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`
there are some wayland related files in `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/` 
Unfortunately, under cosmic, terminal still says `matti@pop-os:~$ qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""` and freezes/crashes on startup.

**Comment by Drakulix** [comment]
Figured out the issue, it is in some upstream project, so I'll need to patch that and then update cosmic-comp to use it. I'll post here once the fix is applied.

**Comment by MattiBRNDMR** [comment]
Awesome, thank you! Looking forward to test the fix.

**Comment by Drakulix** [comment]
Should've been fixed by https://github.com/pop-os/cosmic-comp/commit/989ee95858077aeb0f3e75e44bfeaf607c57f5c3

**Comment by MattiBRNDMR** [comment]
Hey thank you! Is it already available through updating? Installed the latest update for cosmic-comp from like a hour ago, still experiencing the same crash.

**Comment by Drakulix** [comment]
> Hey thank you! Is it already available through updating? Installed the latest update for cosmic-comp from like a hour ago, still experiencing the same crash.

Seeing it as well, investigating.

**Comment by MattiBRNDMR** [comment]
> > Hey thank you! Is it already available through updating? Installed the latest update for cosmic-comp from like a hour ago, still experiencing the same crash.
> 
> Seeing it as well, investigating.

Another observation: It also appears that the os/compositor is not completely frozen, alt tabbing and wiggling the mouse resulted in some of these actions being performed 30-60 seconds later. If there is a way to monitor cosmic-comp events through the terminal or something like that let me know - eager to help! :-)

**Comment by Drakulix** [comment]
bb27b767f2da1fc8e5ad6918afa8ba4fd93f0249 should now truly contain the fix and is live on popdev:master. Just tested it! (You'll need to log out and log in again or reboot after installing the update.)

**Comment by MattiBRNDMR** [comment]
yes, system does not freeze anymore! thank you!
