### ISSUE TITLE
X11 / XWayland Apps Freeze The Display When You Full Screen Them

### ISSUE THREAD

**Issue by HydroLightno** [pop-os/cosmic-comp#702]
I installed the first alpha of cosmic on Pop OS 24.04 using the download link on the official website: https://system76.com/cosmic

My GPU is an Nvidia 1660 and I downloaded the Nvidia ISO on this website so I assume I am using the proprietary drivers as I haven't changed them.

When I full screen X11 apps using the F11 key, the display the app is on completely freezes and if you click the workspaces button on another display, it freezes that as well and I have to restart my computer.

Video of full screen breaking on X11: https://github.com/user-attachments/assets/717d699d-33a9-4874-9265-25cf66a847d7
Video of full screen working fine on wayland with the same app: https://github.com/user-attachments/assets/56a2406a-8811-4f22-b7f1-99823ea5baf6

I have attached 2 videos below of this happening to the brave browser (Flatpak), on one video it is on X11 (I used the xlsclients command to verify this) which was the default for me and when you full screen it, move the mouse to my other display and move it back, the display freezes and i can no longer interact with it.

I then used the brave://flags/#ozone-platform-hint URL to change it to wayland and it full screen works just fine.

I tested this on Minecraft (Flatpak) which froze my screen and VSCode (system package) as I wanted to see if this issue was Flatpak specific which is wasn't as the same problem happened.

I hope this bug helps and it isn't a duplicate as I tried to look for this issue and couldn't find it and I apologize for the video quality.

**Comment by robrotheram** [comment]
Also seeing the same issue, also using the NVIDIA ISO. Was also seeing it in NixOS but re-installed the pop iso to see if it was a issue with my config.

 I was reproducing it by simply full screening a video in YouTube. Might work for a few seconds then would freeze the entire desktop. Audio would keep playing though.  I have attached a snippet from the syslog where I can see cosmic-comp panic  

## Hardware/OS stats
```
 OS: Pop 24.04 noble
 Kernel: x86_64 Linux 6.9.3-76060903-generic
 Uptime: 12m
 Packages: Unknown
 Shell: bash 5.2.21
 Resolution: 1920x1080
 WM: Smithay X WM
 GTK Theme: adw-gtk3-dark [GTK3]
 Disk: 17G / 1.8T (1%)
 CPU: Intel Core i7-6700 @ 8x 4GHz [31.0°C]
 GPU: NVIDIA GeForce GTX 970
 RAM: 4373MiB / 23987MiB
```

## Syslog
```
2024-08-09T11:38:25.362593+01:00 pop-os mtp-probe: checking bus 1, device 15: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11.3/1-11.3.2"
2024-08-09T11:38:25.362810+01:00 pop-os mtp-probe: bus: 1, device: 15 was not an MTP device
2024-08-09T11:38:25.403595+01:00 pop-os mtp-probe: checking bus 1, device 15: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11.3/1-11.3.2"
2024-08-09T11:38:25.403674+01:00 pop-os mtp-probe: bus: 1, device: 15 was not an MTP device
2024-08-09T11:38:26.107704+01:00 pop-os kernel: logitech-hidpp-device 0003:046D:4069.000C: HID++ 4.5 device connected.
2024-08-09T11:38:27.597697+01:00 pop-os kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeout on head 0
2024-08-09T11:38:27.843395+01:00 pop-os cosmic-comp[1485]: Failed to destroy old mode property blob: No such file or directory (os error 2)
2024-08-09T11:38:27.991908+01:00 pop-os cosmic-comp[1485]: thread 'surface-HDMI-A-1' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:726#012   0: <unknown>#012   1: <unknown>#012   2: <unknown>#012   3: <unknown>#012   4: <unknown>#012   5: <unknown>#012   6: <unknown>#012   7: <unknown>#012   8: <unknown>#012   9: <unknown>#012  10: <unknown>#012  11: <unknown>#012  12: <unknown>#012  13: <unknown>#012  14: <unknown>#012  15: <unknown>
2024-08-09T11:38:28.140625+01:00 pop-os cosmic-panel[1543]: com.system76.CosmicAppletStatusArea: Acquired bus name: org.kde.StatusNotifierWatcher
2024-08-09T11:38:28.175899+01:00 pop-os dbus-broker[825]: A security policy denied :1.89 to send method call /org/freedesktop/NetworkManager/Settings:org.freedesktop.NetworkManager.Settings.LoadConnections to org.freedesktop.NetworkManager.
2024-08-09T11:38:28.181940+01:00 pop-os pipewire-pulse[1428]: default: snap_get_audio_permissions: kernel lacks 'fine grained unix mediation'; snap audio permissions won't be honored.
2024-08-09T11:38:28.182856+01:00 pop-os pipewire-pulse[1428]: default: snap_get_audio_permissions: kernel lacks 'fine grained unix mediation'; snap audio permissions won't be honored.
2024-08-09T11:38:38.111170+01:00 pop-os cosmic-comp[1485]: Failed to set new config.
2024-08-09T11:38:38.111346+01:00 pop-os cosmic-comp[1485]: Failed to reset config.
```

**Comment by Drakulix** [comment]
This seems to be the same issue as:
- https://github.com/pop-os/cosmic-comp/issues/556
- https://github.com/pop-os/cosmic-epoch/issues/533
- https://github.com/pop-os/cosmic-epoch/issues/507

So far what I have gathered this seems to affect only Xwayland apps running on nVidia (non-hybrid) systems.

This is likely the underlying issue (a bug of the nvidia driver):
```
2024-08-09T11:38:27.597697+01:00 pop-os kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeout on head 0
```

The result however is the display's thread in cosmic-comp freezing and panic'ing:
```
2024-08-09T11:38:27.991908+01:00 pop-os cosmic-comp[1485]: thread 'surface-HDMI-A-1' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:726#012   0: <unknown>#012   1: <unknown>#012   2: <unknown>#012   3: <unknown>#012   4: <unknown>#012   5: <unknown>#012   6: <unknown>#012   7: <unknown>#012   8: <unknown>#012   9: <unknown>#012  10: <unknown>#012  11: <unknown>#012  12: <unknown>#012  13: <unknown>#012  14: <unknown>#012  15: <unknown>
```

Rendering the output frozen until logging out.

Interestingly this crash is the same, as an edge-case we discovered yesterday when sleeping and resuming on nvidia system. There is an open PR to fix this, could you try and see if that fixes this problem as well? https://github.com/pop-os/cosmic-comp/pull/699

If you are on Pop!_OS (no matter the version) you can update using the following commands:
```
sudo apt-manage add popdev:fix-resume
sudo apt update
sudo apt upgrade
```
Then log out and back in or reboot.

Please remove the test build again afterwards (and then update the system like normal):
```
sudo apt-manage remove popdev-fix-resume
```
```

**Comment by HydroLightno** [comment]
I ran all of the commands in the terminal that you provided and restarted my computer and the same issue still persists.

Here is my terminal output of apt-manage and apt update which I believe shows that I have the updated version of cosmic-comp installed, please let me know if I have done anything wrong:
```
chris@pop-os:~$ apt-manage
Configured Sources:
pop-os-apps - Pop_OS Applications
pop-os-release - Pop_OS Release Sources
system - Pop_OS System Sources
popdev-fix-resume - Pop Development Branch fix-resume
vscode - vscode
chris@pop-os:~$ sudo apt update
[sudo] password for chris:
Hit:1 https://packages.microsoft.com/repos/code stable InRelease
Hit:2 http://apt.pop-os.org/proprietary noble InRelease
Hit:3 http://apt.pop-os.org/release noble InRelease
Hit:4 http://apt.pop-os.org/staging/fix-resume noble InRelease
Hit:5 http://apt.pop-os.org/ubuntu noble InRelease
Hit:6 http://apt.pop-os.org/ubuntu noble-security InRelease
Get:7 http://apt.pop-os.org/ubuntu noble-updates InRelease [126 kB]
Hit:8 http://apt.pop-os.org/ubuntu noble-backports InRelease
Fetched 126 kB in 2s (77.9 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/proprietary'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/release'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
chris@pop-os:~$
```

**Comment by Drakulix** [comment]
No you do certainly have the updated build. Could you reproduce the issue and then run `journalctl --user -b0 _COMM=cosmic-comp` on another not-frozen output and post the result?

**Comment by jsanchezba** [comment]
I also tried aplying that patch. Didn´t work. This is the output of the error i got:
journalctl -n 100 --no-pager
`
ago 09 13:49:05 pop-os systemd[1]: Stopping user@988.service - User Manager for UID 988...
ago 09 13:49:05 pop-os systemd[4783]: Activating special unit exit.target...
ago 09 13:49:05 pop-os systemd[4783]: Stopped target default.target - Main User Target.
ago 09 13:49:05 pop-os systemd[4783]: Stopping filter-chain.service - PipeWire filter chain daemon...
ago 09 13:49:05 pop-os systemd[4783]: Stopping pipewire-pulse.service - PipeWire PulseAudio...
ago 09 13:49:05 pop-os systemd[4783]: Stopping xdg-permission-store.service - sandboxed app permission store...
ago 09 13:49:05 pop-os systemd[4783]: Stopped filter-chain.service - PipeWire filter chain daemon.
ago 09 13:49:05 pop-os systemd[4783]: Stopped xdg-permission-store.service - sandboxed app permission store.
ago 09 13:49:05 pop-os systemd[4783]: Stopped pipewire-pulse.service - PipeWire PulseAudio.
ago 09 13:49:05 pop-os wireplumber[4798]: stopped by signal: Terminado
ago 09 13:49:05 pop-os systemd[4783]: Stopping wireplumber.service - Multimedia Service Session Manager...
ago 09 13:49:05 pop-os wireplumber[4798]: disconnected from pipewire
ago 09 13:49:05 pop-os systemd[4783]: Stopped wireplumber.service - Multimedia Service Session Manager.
ago 09 13:49:05 pop-os systemd[4783]: Stopping pipewire.service - PipeWire Multimedia Service...
ago 09 13:49:05 pop-os systemd[4783]: Stopped pipewire.service - PipeWire Multimedia Service.
ago 09 13:49:05 pop-os systemd[4783]: Stopped target basic.target - Basic System.
ago 09 13:49:05 pop-os systemd[4783]: Stopped target paths.target - Paths.
ago 09 13:49:05 pop-os systemd[4783]: Stopped target sockets.target - Sockets.
ago 09 13:49:05 pop-os systemd[4783]: Stopped target timers.target - Timers.
ago 09 13:49:05 pop-os systemd[4783]: Stopped launchpadlib-cache-clean.timer - Clean up old files in the Launchpadlib cache.
ago 09 13:49:05 pop-os systemd[4783]: Closed dirmngr.socket - GnuPG network certificate management daemon.
ago 09 13:49:05 pop-os systemd[4783]: Closed gcr-ssh-agent.socket - GCR ssh-agent wrapper.
ago 09 13:49:05 pop-os systemd[4783]: Closed gpg-agent-browser.socket - GnuPG cryptographic agent and passphrase cache (access for web browsers).
ago 09 13:49:05 pop-os systemd[4783]: Closed gpg-agent-extra.socket - GnuPG cryptographic agent and passphrase cache (restricted).
ago 09 13:49:05 pop-os systemd[4783]: Stopping gpg-agent-ssh.socket - GnuPG cryptographic agent (ssh-agent emulation)...
ago 09 13:49:05 pop-os systemd[4783]: Closed gpg-agent.socket - GnuPG cryptographic agent and passphrase cache.
ago 09 13:49:05 pop-os systemd[4783]: Closed keyboxd.socket - GnuPG public key management service.
ago 09 13:49:05 pop-os systemd[4783]: Closed pipewire-pulse.socket - PipeWire PulseAudio.
ago 09 13:49:05 pop-os systemd[4783]: Closed pipewire.socket - PipeWire Multimedia System Sockets.
ago 09 13:49:05 pop-os systemd[4783]: Closed pk-debconf-helper.socket - debconf communication socket.
ago 09 13:49:05 pop-os dbus-broker[4801]: Dispatched 334 messages @ 2(±3)μs / message.
ago 09 13:49:05 pop-os systemd[4783]: Stopping dbus-broker.service - D-Bus User Message Bus...
ago 09 13:49:05 pop-os systemd[4783]: Stopped dbus-broker.service - D-Bus User Message Bus.
ago 09 13:49:05 pop-os systemd[4783]: Removed slice session.slice - User Core Session Slice.
ago 09 13:49:05 pop-os systemd[4783]: Closed dbus.socket - D-Bus User Message Bus Socket.
ago 09 13:49:05 pop-os systemd[4783]: Closed gpg-agent-ssh.socket - GnuPG cryptographic agent (ssh-agent emulation).
ago 09 13:49:05 pop-os systemd[4783]: Removed slice app.slice - User Application Slice.
ago 09 13:49:05 pop-os systemd[4783]: Reached target shutdown.target - Shutdown.
ago 09 13:49:05 pop-os systemd[4783]: Finished systemd-exit.service - Exit the Session.
ago 09 13:49:05 pop-os systemd[4783]: Reached target exit.target - Exit the Session.
ago 09 13:49:05 pop-os (sd-pam)[4784]: pam_unix(systemd-user:session): session closed for user cosmic-greeter
ago 09 13:49:05 pop-os systemd[1]: user@988.service: Deactivated successfully.
ago 09 13:49:05 pop-os systemd[1]: Stopped user@988.service - User Manager for UID 988.
ago 09 13:49:05 pop-os systemd[1]: Stopping user-runtime-dir@988.service - User Runtime Directory /run/user/988...
ago 09 13:49:05 pop-os systemd[1]: run-user-988.mount: Deactivated successfully.
ago 09 13:49:05 pop-os systemd[1]: user-runtime-dir@988.service: Deactivated successfully.
ago 09 13:49:05 pop-os systemd[1]: Stopped user-runtime-dir@988.service - User Runtime Directory /run/user/988.
ago 09 13:49:05 pop-os systemd[1]: Removed slice user-988.slice - User Slice of UID 988.
ago 09 13:49:05 pop-os systemd[1]: user-988.slice: Consumed 6.110s CPU time.
ago 09 13:49:19 pop-os systemd[1408]: Started app-cosmic-com.system76.CosmicAppList-5728.scope - Application launched by COSMIC.
ago 09 13:49:19 pop-os systemd[1]: bluetooth.service - Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
ago 09 13:49:26 pop-os systemd[1]: systemd-localed.service: Deactivated successfully.
ago 09 13:49:57 pop-os dbus-broker[780]: A security policy denied :1.209 to send method call /org/freedesktop/NetworkManager/Settings:org.freedesktop.NetworkManager.Settings.LoadConnections to org.freedesktop.NetworkManager.
ago 09 13:49:57 pop-os dbus-broker[780]: A security policy denied :1.208 to send method call /org/freedesktop/NetworkManager/Settings:org.freedesktop.NetworkManager.Settings.LoadConnections to org.freedesktop.NetworkManager.
ago 09 13:50:09 pop-os cosmic-comp[4976]: using legacy fbadd
ago 09 13:50:09 pop-os kernel: nvidia-modeset: ERROR: Invalid request parameters, planePitch or rmObjectSizeInBytes, passed during surface registration
ago 09 13:50:09 pop-os kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00002b00] Failed to apply atomic modeset.  Error code: -22
`

**Comment by Drakulix** [comment]
This seems to be more and more an issue with direct-scanout of Xwayland surfaces on the nvidia-driver. Thanks for the logs, very helpful.

**Comment by Drakulix** [comment]
Issue found, downstream patch is necessary: https://github.com/Smithay/smithay/pull/1501

This will be fixed once that (or an alternative approach to work around the buggy nvidia driver) is merged **and** cosmic-comp is updated to use the new version.

**Comment by Drakulix** [comment]
Should be fixed by 0916d3599a91fe40503209e0431fcc888fa6b867

**Comment by RinLovesYou** [comment]
> Should be fixed by [0916d35](https://github.com/pop-os/cosmic-comp/commit/0916d3599a91fe40503209e0431fcc888fa6b867)

can confirm, fixed! thank you for the quick work!

**Comment by ryzendew** [comment]
not fully fixed i updated to the newest and still have issues

**Comment by ryzendew** [comment]
![screenshot-2024-08-10-17-12-11](https://github.com/user-attachments/assets/4212c7a8-57cd-4c11-af09-dd25f883bd6a)
Guild wars 2 
Visage also does this 
Guild wars 2 on steam doesn't start the full game and just sits 
re8 works until you put it in fullscreen
runescape 3 works but only with steam overlay disabled fully
dead island 2 works in window mode but not fullscreen and if i try it freezes

**Comment by drakon64** [comment]
Final Fantasy XIV still freezes when switching from Borderless Windowed to Full Screen

**Comment by Drakulix** [comment]
Could any of you then please share some cosmic-comp and kernel logs?

**Comment by drakon64** [comment]
The kernel isn't logging anything and `cosmic-comp` doesn't appear at all in `journalctl`.

While rendering itself is frozen, audio still plays and the in-game menu still seemingly reacts to input if I click where I'd expect buttons to be (the audio plays).

**Comment by Animo78** [comment]
The update didn´t work for me neither, but I did notice some weird things (Sorry I might not be very clear, but I'm a n00b.

```
apt-manage
Configured Sources:
pop-os-apps - Pop_OS Applications
pop-os-release - Pop_OS Release Sources
system - Pop_OS System Sources
nordvpn - nordvpn
docker - docker
system76-dev-ubuntu-stable-jammy - system76-dev-ubuntu-stable-jammy
```
I'm running on 3440x1440 but I see resolution of 1024x768
```  neofetch
             /////////////                Johnny@pop-os
         /////////////////////            --------------
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64
    //////7676767676*//////////////       Host: 90Q8003JMH Legion T7 34IMZ5
   /////76767//7676767//////////////      Kernel: 6.9.3-76060903-generic
  /////767676///*76767///////////////     Uptime: 15 mins
 ///////767676///76767.///7676*///////    Packages: 2648 (dpkg), 18 (flatpak)
/////////767676//76767///767676////////   Shell: bash 5.1.16
//////////76767676767////76767/////////   Resolution: 1024x768
///////////76767676//////7676//////////   DE: COSMIC
////////////,7676,///////767///////////   Theme: Pop-dark [GTK3]
/////////////*7676///////76////////////   Icons: Pop [GTK3]
///////////////7676////////////////////   Terminal: cosmic-term
 ///////////////7676///767////////////    CPU: Intel i9-10900K (20) @ 5.300GHz
  //////////////////////'////////////     GPU: NVIDIA GeForce RTX 3080
   //////.7676767676767676767,//////      Memory: 2588MiB / 31901MiB
    /////767676767676767676767/////
      ///////////////////////////
         /////////////////////
             /////////////
             

> 
```
I uploaded a screenshot, where you see the button bar on the right, but when I move my mouse, I have to move my mouse left of the golden cube in the image, to be able to use the buttons on the far right.
![screenshot-2024-08-16-19-44-45](https://github.com/user-attachments/assets/2757616c-3df4-482f-baa3-1a2b9d1058d7)

It might not be the most useful information, but I tested it with 5 different games, 2 of these I got in borderless full screen (the others I'm uncertain of and I'm unable to check cause of this bug) but they both seem bothered by this bug in borderless full screen as well.

Let me know if I can provide any more information.

**Comment by Animo78** [comment]
@Drakulix I want to share the cosmic-comp and kernel logs but I want to do it in a safe way, don´t know what I might share with them, how do I get them to you?

n00b here.

**Comment by komali2** [comment]
> @Drakulix I want to share the cosmic-comp and kernel logs but I want to do it in a safe way, don´t know what I might share with them, how do I get them to you?
> 
> n00b here.

There's not really any identifying information in these logs. It's relatively generic information about what kind of devices are connected to your computer and what the various components of your OS are doing. Unless you're maintaining super strict opsec, there's no risk in sharing these logs.
