### ISSUE TITLE
Reaper DAW missing drop-down options

### ISSUE THREAD

**Issue by TotalChaos05** [pop-os/cosmic-comp#966]
When opening any menu in reaper (both drop-downs and right clicking) the created menu is invisible, but you can still click on the invisible options.
I would add some screengrabs/recordings but i cant get it to work atm

**Comment by ragardner** [comment]
I am having identical symptoms but with python tkinter apps

https://github.com/pop-os/cosmic-comp/issues/971

**Comment by TotalChaos05** [comment]
@ragardner 
was it fixed by [this](https://github.com/pop-os/cosmic-comp/commit/eb64fdaf8fe4f5e6957a35e74004b183acc905c8) ?
i dont have cosmic installed atm but ill check when i can

**Comment by TotalChaos05** [comment]
it wasnt fixed by it
is there any info i can give to help debug?

**Comment by terratrax** [comment]
Confirming that Tkinter based gui menu cascades still do not work in Alpha 5.

**Comment by ids1024** [comment]
https://github.com/Smithay/smithay/pull/1701 should improve things.

**Comment by WatchMkr** [comment]
Tested and appears fixed in Reaper.
